Split HAVE_IOS_REGISTER_CALLBACK from HAVE_IOS_XALLOC.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@13065 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12561,8 +12561,12 @@ _ACEOF
 fi
 
 
-echo "$as_me:$LINENO: checking for ios(_base)::xalloc and related functions" >&5
-echo $ECHO_N "checking for ios(_base)::xalloc and related functions... $ECHO_C" >&6
+# Avoid false negatives due to split.
+test "$ncbi_cv_func_ios_xalloc" = no \
+  -a -z "${ncbi_cv_func_ios_register_callback+set}"  &&  \
+    unset ncbi_cv_func_ios_xalloc
+echo "$as_me:$LINENO: checking for ios(_base)::xalloc" >&5
+echo $ECHO_N "checking for ios(_base)::xalloc... $ECHO_C" >&6
 if test "${ncbi_cv_func_ios_xalloc+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -12578,7 +12582,6 @@ int
 main ()
 {
 std::cout.pword(std::ios::xalloc());
-         std::cout.register_callback(0, std::ios::erase_event);
   ;
   return 0;
 }
@@ -12610,6 +12613,59 @@ if test "$ncbi_cv_func_ios_xalloc" = yes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_IOS_XALLOC 1
+_ACEOF
+
+fi
+
+
+echo "$as_me:$LINENO: checking for ios(_base)::register_callback" >&5
+echo $ECHO_N "checking for ios(_base)::register_callback... $ECHO_C" >&6
+if test "${ncbi_cv_func_ios_register_callback+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <iostream>
+int
+main ()
+{
+std::cout.register_callback(0, std::ios::erase_event);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_func_ios_register_callback=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ncbi_cv_func_ios_register_callback=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_func_ios_register_callback" >&5
+echo "${ECHO_T}$ncbi_cv_func_ios_register_callback" >&6
+if test "$ncbi_cv_func_ios_register_callback" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IOS_REGISTER_CALLBACK 1
 _ACEOF
 
 fi
