New tests: HAVE_IOS_XALLOC, AUTOMATIC_STREAMBUF_DESTRUCTION
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@8236 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7697,6 +7697,132 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking for ios(_base)::xalloc and related functions" >&5
+echo $ECHO_N "checking for ios(_base)::xalloc and related functions... $ECHO_C" >&6
+if test "${ncbi_cv_func_ios_xalloc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <iostream>
+int
+main ()
+{
+std::cout.pword(std::ios::xalloc());
+         std::cout.register_callback(0, std::ios::erase_event);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_func_ios_xalloc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ncbi_cv_func_ios_xalloc=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_func_ios_xalloc" >&5
+echo "${ECHO_T}$ncbi_cv_func_ios_xalloc" >&6
+if test "$ncbi_cv_func_ios_xalloc" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IOS_XALLOC 1
+_ACEOF
+
+fi
+
+
+echo "$as_me:$LINENO: checking whether C++ streams delete their buffers" >&5
+echo $ECHO_N "checking whether C++ streams delete their buffers... $ECHO_C" >&6
+if test "${ncbi_cv_cxx_auto_sb_dest+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  ncbi_cv_cxx_auto_sb_dest=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <iostream>
+         int status = 1;
+         class mybuf : public std::streambuf
+         {
+         public:
+             ~mybuf() { status = 0; }
+         };
+         class mystream : public std::iostream
+         {
+         public:
+               mystream() { init(new mybuf); }
+         };
+
+int
+main ()
+{
+{ mystream s; }  return status;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_cxx_auto_sb_dest=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+ncbi_cv_cxx_auto_sb_dest=no
+fi
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_cxx_auto_sb_dest" >&5
+echo "${ECHO_T}$ncbi_cv_cxx_auto_sb_dest" >&6
+# Rare, so assume "no" when cross-compiling
+if test "$ncbi_cv_cxx_auto_sb_dest" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define AUTOMATIC_STREAMBUF_DESTRUCTION 1
+_ACEOF
+
+fi
+
+
+
 echo "$as_me:$LINENO: checking for std::char_traits::" >&5
 echo $ECHO_N "checking for std::char_traits::... $ECHO_C" >&6
 if test "${ncbi_cv_type_char_traits+set}" = set; then
