Check for LZO (as a possibly bundled library); clarify some messages.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@33034 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX MT_SFX DLL_LIB_SETTING STATIC USUAL_AND_DLL USUAL_AND_LIB LN_S RANLIB ac_ct_RANLIB AR STRIP LORDER TSORT DISTCC CCACHE TAIL EGREP VALGRIND_PATH CXXCPP AMQ CPP Z_INCLUDE Z_LIBS BZ2_INCLUDE BZ2_LIBS PCRE_INCLUDE PCRE_LIBS GNUTLS_INCLUDE GNUTLS_LIBS OPENSSL_INCLUDE OPENSSL_LIBS FTDS8_INCLUDE FTDS8_LIBS FTDS8_LIB FTDS63_INCLUDE FTDS63_LIBS FTDS63_LIB FTDS64_INCLUDE FTDS64_LIBS FTDS64_LIB FTDS_INCLUDE FTDS_LIBS FTDS_LIB freetds ftds8 ftds63 ftds64 mysql_config PYTHON PYTHON_INCLUDE PYTHON_LIBS PYTHON23 PYTHON23_INCLUDE PYTHON23_LIBS PYTHON24 PYTHON24_INCLUDE PYTHON24_LIBS PYTHON25 PYTHON25_INCLUDE PYTHON25_LIBS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS EXPAT_INCLUDE EXPAT_LIBS SABLOT_INCLUDE SABLOT_LIBS LIBXML_INCLUDE LIBXML_LIBS LIBXSLT_INCLUDE LIBXSLT_LIBS SQLITE_INCLUDE SQLITE_LIBS SQLITE3_INCLUDE SQLITE3_LIBS OECHEM_INCLUDE OECHEM_LIBS JPEG_INCLUDE JPEG_LIBS PNG_INCLUDE PNG_LIBS TIFF_INCLUDE TIFF_LIBS UNGIF_INCLUDE UNGIF_LIBS GIF_INCLUDE GIF_LIBS XPM_INCLUDE XPM_LIBS freetype_config PROJECTS signature build_root top_srcdir srcdir status_dir builddir runpath ncbi_runpath LINK C_LINK TAIL_N EGREP_Q FAST_CFLAGS FAST_CXXFLAGS DEPFLAGS DEPFLAGS_POST FAST_LDFLAGS C_LIBS GCCPCH RUNPATH_ORIGIN D_SFX DEBUG_SFX LIB_OR_DLL FORCE_STATIC_LIB LINK_DLL has_dll_loadable LINK_LOADABLE CFLAGS_DLL CXXFLAGS_DLL ALLOW_UNDEF FORBID_UNDEF OPT_GROUPS local_lbsm ncbi_crypt CONNEXT XCONNEXT serial bdb dbapi objects gui algo app internal check CHECK_ARG CHECK_TOOLS script_shell make_shell obj_ext lib_pre lib_l_pre lib_ext dll_ext loadable_ext lib_l_ext exe_ext f_compile f_outobj f_outlib f_libpath f_runpath f_outexe BDB_LIB BDB_CACHE_LIB THREAD_LIBS NETWORK_LIBS NETWORK_PURE_LIBS RESOLVER_LIBS MATH_LIBS KSTAT_LIBS RPCSVC_LIBS CRYPT_LIBS DL_LIBS RT_LIBS DEMANGLE_LIBS ICONV_LIBS Z_LIB BZ2_LIB PCREPOSIX_LIBS PCRE_LIB TLS_INCLUDE TLS_LIBS SYBASE_PATH SYBASE_INCLUDE SYBASE_LIBS SYBASE_DLLS SYBASE_DBLIBS MYSQL_INCLUDE MYSQL_LIBS BERKELEYDB_INCLUDE BERKELEYDB_LIBS BERKELEYDB_STATIC_LIBS BERKELEYDB_CXX_LIBS BERKELEYDB_CXX_STATIC_LIBS ODBC_INCLUDE ODBC_LIBS CPPUNIT_INCLUDE CPPUNIT_LIBS BOOST_INCLUDE BOOST_LIBPATH BOOST_TAG BOOST_REGEX_LIBS BOOST_REGEX_STATIC_LIBS BOOST_TEST_PEM_LIBS BOOST_TEST_PEM_STATIC_LIBS BOOST_TEST_TEM_LIBS BOOST_TEST_TEM_STATIC_LIBS BOOST_TEST_UTF_LIBS BOOST_TEST_UTF_STATIC_LIBS BOOST_THREAD_LIBS BOOST_THREAD_STATIC_LIBS NCBI_C_INCLUDE NCBI_C_LIBPATH OPENGL_INCLUDE OPENGL_LIBS OSMESA_INCLUDE OSMESA_LIBS GLUT_INCLUDE GLUT_LIBS FLTK_INCLUDE FLTK_LIBS FLTK_LIBS_GL FLTK_LIBS_IMAGES FLTK_LIBS_ALL FLTK_STATIC_LIBS FLTK_STATIC_LIBS_GL FLTK_STATIC_LIBS_IMAGES FLTK_STATIC_LIBS_ALL FLTK_CONFIG WXWIN_INCLUDE WXWIN_LIBS WXWIN_STATIC_LIBS WXWIN_GL_LIBS WXWIN_GL_STATIC_LIBS WXWIN_POST_LINK WXWIDGETS_INCLUDE WXWIDGETS_LIBS WXWIDGETS_STATIC_LIBS WXWIDGETS_GL_LIBS WXWIDGETS_GL_STATIC_LIBS WXWIDGETS_POST_LINK FASTCGI_INCLUDE FASTCGI_LIBS FASTCGI_OBJS NCBI_SSS_INCLUDE NCBI_SSS_LIBPATH LIBSSSUTILS LIBSSSDB sss ssssrv stax SP_INCLUDE SP_LIBS ORBACUS_INCLUDE ORBACUS_LIBPATH LIBOB LIBIMR ICU_CONFIG ICU_INCLUDE ICU_LIBS ICU_STATIC_LIBS EXPAT_STATIC_LIBS SABLOT_STATIC_LIBS LIBXML_STATIC_LIBS LIBXSLT_STATIC_LIBS XERCES_INCLUDE XERCES_LIBS XERCES_STATIC_LIBS XALAN_INCLUDE XALAN_LIBS XALAN_STATIC_LIBS FREETYPE_INCLUDE FREETYPE_LIBS NCBI_C_ncbi BINCOPY APP_NOCOPY APP_OR_NULL IF_REBUILDING_LIBS IF_REBUILDING_CONDITIONALLY CC_FILTER CXX_FILTER AR_FILTER LINK_FILTER CC_WRAPPER CXX_WRAPPER AR_WRAPPER LINK_WRAPPER KeepStateTarget Rules serial_ws50_rtti_kludge ncbicntr UNIX_SRC UNIX_USR_PROJ compiler compiler_root compiler_version COMPILER OSTYPE NCBI_PLATFORM_BITS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX MT_SFX DLL_LIB_SETTING STATIC USUAL_AND_DLL USUAL_AND_LIB LN_S RANLIB ac_ct_RANLIB AR STRIP LORDER TSORT DISTCC CCACHE TAIL EGREP VALGRIND_PATH CXXCPP AMQ CPP Z_INCLUDE Z_LIBS BZ2_INCLUDE BZ2_LIBS LZO_INCLUDE LZO_LIBS PCRE_INCLUDE PCRE_LIBS GNUTLS_INCLUDE GNUTLS_LIBS OPENSSL_INCLUDE OPENSSL_LIBS FTDS8_INCLUDE FTDS8_LIBS FTDS8_LIB FTDS63_INCLUDE FTDS63_LIBS FTDS63_LIB FTDS64_INCLUDE FTDS64_LIBS FTDS64_LIB FTDS_INCLUDE FTDS_LIBS FTDS_LIB freetds ftds8 ftds63 ftds64 mysql_config PYTHON PYTHON_INCLUDE PYTHON_LIBS PYTHON23 PYTHON23_INCLUDE PYTHON23_LIBS PYTHON24 PYTHON24_INCLUDE PYTHON24_LIBS PYTHON25 PYTHON25_INCLUDE PYTHON25_LIBS X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS EXPAT_INCLUDE EXPAT_LIBS SABLOT_INCLUDE SABLOT_LIBS LIBXML_INCLUDE LIBXML_LIBS LIBXSLT_INCLUDE LIBXSLT_LIBS SQLITE_INCLUDE SQLITE_LIBS SQLITE3_INCLUDE SQLITE3_LIBS OECHEM_INCLUDE OECHEM_LIBS JPEG_INCLUDE JPEG_LIBS PNG_INCLUDE PNG_LIBS TIFF_INCLUDE TIFF_LIBS UNGIF_INCLUDE UNGIF_LIBS GIF_INCLUDE GIF_LIBS XPM_INCLUDE XPM_LIBS freetype_config PROJECTS signature build_root top_srcdir srcdir status_dir builddir runpath ncbi_runpath LINK C_LINK TAIL_N EGREP_Q FAST_CFLAGS FAST_CXXFLAGS DEPFLAGS DEPFLAGS_POST FAST_LDFLAGS C_LIBS GCCPCH RUNPATH_ORIGIN D_SFX DEBUG_SFX LIB_OR_DLL FORCE_STATIC_LIB LINK_DLL has_dll_loadable LINK_LOADABLE CFLAGS_DLL CXXFLAGS_DLL ALLOW_UNDEF FORBID_UNDEF OPT_GROUPS local_lbsm ncbi_crypt CONNEXT XCONNEXT serial bdb dbapi objects gui algo app internal check CHECK_ARG CHECK_TOOLS script_shell make_shell obj_ext lib_pre lib_l_pre lib_ext dll_ext loadable_ext lib_l_ext exe_ext f_compile f_outobj f_outlib f_libpath f_runpath f_outexe BDB_LIB BDB_CACHE_LIB THREAD_LIBS NETWORK_LIBS NETWORK_PURE_LIBS RESOLVER_LIBS MATH_LIBS KSTAT_LIBS RPCSVC_LIBS CRYPT_LIBS DL_LIBS RT_LIBS DEMANGLE_LIBS ICONV_LIBS Z_LIB BZ2_LIB LZO_LIB PCREPOSIX_LIBS PCRE_LIB TLS_INCLUDE TLS_LIBS SYBASE_PATH SYBASE_INCLUDE SYBASE_LIBS SYBASE_DLLS SYBASE_DBLIBS MYSQL_INCLUDE MYSQL_LIBS BERKELEYDB_INCLUDE BERKELEYDB_LIBS BERKELEYDB_STATIC_LIBS BERKELEYDB_CXX_LIBS BERKELEYDB_CXX_STATIC_LIBS ODBC_INCLUDE ODBC_LIBS CPPUNIT_INCLUDE CPPUNIT_LIBS BOOST_INCLUDE BOOST_LIBPATH BOOST_TAG BOOST_REGEX_LIBS BOOST_REGEX_STATIC_LIBS BOOST_TEST_PEM_LIBS BOOST_TEST_PEM_STATIC_LIBS BOOST_TEST_TEM_LIBS BOOST_TEST_TEM_STATIC_LIBS BOOST_TEST_UTF_LIBS BOOST_TEST_UTF_STATIC_LIBS BOOST_THREAD_LIBS BOOST_THREAD_STATIC_LIBS NCBI_C_INCLUDE NCBI_C_LIBPATH OPENGL_INCLUDE OPENGL_LIBS OSMESA_INCLUDE OSMESA_LIBS GLUT_INCLUDE GLUT_LIBS FLTK_INCLUDE FLTK_LIBS FLTK_LIBS_GL FLTK_LIBS_IMAGES FLTK_LIBS_ALL FLTK_STATIC_LIBS FLTK_STATIC_LIBS_GL FLTK_STATIC_LIBS_IMAGES FLTK_STATIC_LIBS_ALL FLTK_CONFIG WXWIN_INCLUDE WXWIN_LIBS WXWIN_STATIC_LIBS WXWIN_GL_LIBS WXWIN_GL_STATIC_LIBS WXWIN_POST_LINK WXWIDGETS_INCLUDE WXWIDGETS_LIBS WXWIDGETS_STATIC_LIBS WXWIDGETS_GL_LIBS WXWIDGETS_GL_STATIC_LIBS WXWIDGETS_POST_LINK FASTCGI_INCLUDE FASTCGI_LIBS FASTCGI_OBJS NCBI_SSS_INCLUDE NCBI_SSS_LIBPATH LIBSSSUTILS LIBSSSDB sss ssssrv stax SP_INCLUDE SP_LIBS ORBACUS_INCLUDE ORBACUS_LIBPATH LIBOB LIBIMR ICU_CONFIG ICU_INCLUDE ICU_LIBS ICU_STATIC_LIBS EXPAT_STATIC_LIBS SABLOT_STATIC_LIBS LIBXML_STATIC_LIBS LIBXSLT_STATIC_LIBS XERCES_INCLUDE XERCES_LIBS XERCES_STATIC_LIBS XALAN_INCLUDE XALAN_LIBS XALAN_STATIC_LIBS FREETYPE_INCLUDE FREETYPE_LIBS NCBI_C_ncbi BINCOPY APP_NOCOPY APP_OR_NULL IF_REBUILDING_LIBS IF_REBUILDING_CONDITIONALLY CC_FILTER CXX_FILTER AR_FILTER LINK_FILTER CC_WRAPPER CXX_WRAPPER AR_WRAPPER LINK_WRAPPER KeepStateTarget Rules serial_ws50_rtti_kludge ncbicntr UNIX_SRC UNIX_USR_PROJ compiler compiler_root compiler_version COMPILER OSTYPE NCBI_PLATFORM_BITS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -909,6 +909,8 @@ Optional Packages:
  --without-z             use internal copy of zlib
  --with-bz2=DIR          use bzlib installation in DIR
  --without-bz2           use internal copy of bzlib
+ --with-lzo=DIR          use LZO installation in DIR
+ --without-lzo           use internal copy of LZO
  --with-pcre=DIR         use PCRE installation in DIR
  --without-pcre          use internal copy of PCRE
  --with-gnutls=DIR       use GNUTLS installation in DIR
@@ -1784,6 +1786,18 @@ if test "${with_bz2b+set}" = set; then
 
 fi;
 
+# Check whether --with-lzo or --without-lzo was given.
+if test "${with_lzo+set}" = set; then
+  withval="$with_lzo"
+
+fi;
+
+# Check whether --with-lzo2 or --without-lzo2 was given.
+if test "${with_lzo2+set}" = set; then
+  withval="$with_lzo2"
+
+fi;
+
 # Check whether --with-pcre or --without-pcre was given.
 if test "${with_pcre+set}" = set; then
   withval="$with_pcre"
@@ -2337,7 +2351,7 @@ check static-exe bin-release strip version lfs pch caution ccache distcc \
 flat-makefile \
 ncbi-c wxwin wxwidgets fastcgi sss sssdb sssutils included-sss \
 geo included-geo \
-z bz2 pcre gnutls openssl sybase sybase-local sybase-new \
+z bz2 lzo pcre gnutls openssl sybase sybase-local sybase-new \
 ftds mysql orbacus freetype fltk \
 opengl mesa glut bdb python sqlite sqlite3 icu cppunit boost boost-tag \
 sp expat sablot libxml libxslt xerces xalan oechem gif jpeg tiff png xpm \
@@ -2376,7 +2390,7 @@ echo "$as_me: error: $x_arg:  requires value;  use --help to show usage" >&2;}
       | --cache-file=* | --build=* | --host=* | --prefix=* | --exec-prefix=* \
       | --libdir=* | --bindir=* | --includedir=* \
       | [A-Z]*=* \
-      | --with-z=* | --with-bz2=* | --with-pcre=* \
+      | --with-z=* | --with-bz2=* | --with-lzo=* | --with-pcre=* \
       | --with-gnutls=* | --with-openssl=* \
       | --with-sybase-local=* | --with-wxwin=* | --with-wxwidgets=* \
       | --with-ftds=* | --with-mysql=* | --with-fltk=* | --with-fastcgi=* \
@@ -19102,8 +19116,8 @@ _ACEOF
 
 if test -z "$Z_LIBS"; then
    zlocal=util/compress/zlib
-   { echo "$as_me:$LINENO: using local copy in $zlocal" >&5
-echo "$as_me: using local copy in $zlocal" >&6;}
+   { echo "$as_me:$LINENO: using local zlib copy in $zlocal" >&5
+echo "$as_me: using local zlib copy in $zlocal" >&6;}
    Z_PATH="<$zlocal>"
    Z_INCLUDE="-I\$(includedir)/$zlocal -I\$(includedir0)/$zlocal"
    # Z_LIBS="-lz"
@@ -19215,8 +19229,8 @@ _ACEOF
 
 if test -z "$BZ2_LIBS"; then
    bzlocal=util/compress/bzip2
-   { echo "$as_me:$LINENO: using local copy in $bzlocal" >&5
-echo "$as_me: using local copy in $bzlocal" >&6;}
+   { echo "$as_me:$LINENO: using local bzlib copy in $bzlocal" >&5
+echo "$as_me: using local bzlib copy in $bzlocal" >&6;}
    BZ2_PATH="<$bzlocal>"
    BZ2_INCLUDE="-I\$(includedir)/$bzlocal -I\$(includedir0)/$bzlocal"
    # BZ2_LIBS="-lbz2"
@@ -19228,6 +19242,122 @@ _ACEOF
 
    	  WithPackages="$WithPackages${WithPackagesSep}BZ2"; WithPackagesSep=" "
    	  WithPackages="$WithPackages${WithPackagesSep}LocalBZ2"; WithPackagesSep=" "
+fi
+
+if test "$with_lzo" != "no"; then
+    case "$with_lzo" in
+       yes | "" ) ;;
+       *        ) LZO_PATH=$with_lzo ;;
+    esac
+    if test -d "$LZO_PATH"; then
+       in_path=" in $LZO_PATH"
+       if test -z "$LZO_INCLUDE" -a -d "$LZO_PATH/include"; then
+          LZO_INCLUDE="-I$LZO_PATH/include"
+       fi
+       if test -n "$LZO_LIBPATH"; then
+          :
+       elif test -d "$LZO_PATH/lib${bit64_sfx}"; then
+          LZO_LIBPATH="-L$LZO_PATH/lib${bit64_sfx} ${CONF_f_runpath}$LZO_PATH/lib${bit64_sfx}"
+       elif test -d "$LZO_PATH/lib"; then
+          LZO_LIBPATH="-L$LZO_PATH/lib ${CONF_f_runpath}$LZO_PATH/lib"
+       fi
+       LZO_LIBS="$LZO_LIBPATH -llzo "
+    else
+       LZO_INCLUDE=""
+       LZO_LIBS="-llzo "
+       in_path=
+    fi
+    echo "$as_me:$LINENO: checking for liblzo$in_path" >&5
+echo $ECHO_N "checking for liblzo$in_path... $ECHO_C" >&6
+if test "${ncbi_cv_lib_lzo+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  CPPFLAGS=" $LZO_INCLUDE $orig_CPPFLAGS"
+       LIBS="$LZO_LIBS  $orig_LIBS"
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <lzo1x.h>
+int
+main ()
+{
+lzo_uint32 c = lzo_crc32(0, "foo", 3);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_lib_lzo=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ncbi_cv_lib_lzo=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_lib_lzo" >&5
+echo "${ECHO_T}$ncbi_cv_lib_lzo" >&6
+    if test "$ncbi_cv_lib_lzo" = "no"; then
+       with_lzo="no"
+    fi
+ fi
+ if test "$with_lzo" = "no"; then
+    LZO_PATH="No_LZO"
+    LZO_INCLUDE=
+    LZO_LIBS=
+ else
+    	  WithPackages="$WithPackages${WithPackagesSep}LZO"; WithPackagesSep=" "
+    LZO_INCLUDE=" $LZO_INCLUDE"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBLZO 1
+_ACEOF
+
+ fi
+
+
+
+if test -z "$LZO_LIBS"; then
+   lzolocal=util/compress/lzo
+   { echo "$as_me:$LINENO: using local LZO copy in $lzolocal" >&5
+echo "$as_me: using local LZO copy in $lzolocal" >&6;}
+   LZO_PATH="<$lzolocal>"
+   LZO_INCLUDE="-I\$(includedir)/$lzolocal -I\$(includedir0)/$lzolocal"
+   # LZO_LIBS="-llzo"
+   LZO_LIB="lzo"
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_LOCAL_LZO 1
+_ACEOF
+
+   	  WithPackages="$WithPackages${WithPackagesSep}LZO"; WithPackagesSep=" "
+   	  WithPackages="$WithPackages${WithPackagesSep}LocalLZO"; WithPackagesSep=" "
 fi
 
 if test -z "$PCRE_PATH"  &&  pcre-config --version >/dev/null 2>&1; then
@@ -19335,8 +19465,8 @@ _ACEOF
 
 if test -z "$PCRE_LIBS"; then
    pcrelocal=util/regexp
-   { echo "$as_me:$LINENO: using local copy in $pcrelocal" >&5
-echo "$as_me: using local copy in $pcrelocal" >&6;}
+   { echo "$as_me:$LINENO: using local PCRE copy in $pcrelocal" >&5
+echo "$as_me: using local PCRE copy in $pcrelocal" >&6;}
    PCRE_PATH="<$pcrelocal>"
    PCRE_INCLUDE="-I\$(includedir)/$pcrelocal -I\$(includedir0)/$pcrelocal"
    # PCRE_LIBS="-lregexp"
@@ -27520,7 +27650,7 @@ for x in MT DLL MSWin unix AIX BSD Cygwin CygwinMT Darwin IRIX Linux OSF Solaris
           ;;
       esac
    done
-  for x in Z LocalZ BZ2 LocalBZ2 PCRE LocalPCRE GNUTLS OPENSSL Sybase DBLib FreeTDS MySQL BerkeleyDB BerkeleyDB++ ODBC PYTHON PYTHON23 PYTHON24 PYTHON25 CPPUNIT Boost.Regex Boost.Spirit Boost.Test Boost.Threads C-Toolkit OpenGL MESA GLUT FLTK wxWindows wxWidgets Fast-CGI SSSUTILS SSSDB SP ORBacus ICU EXPAT SABLOT LIBXML LIBXSLT Xerces Xalan SQLITE SQLITE3 OECHEM JPEG PNG TIFF UNGIF GIF XPM FreeType; do
+  for x in Z LocalZ BZ2 LocalBZ2 LZO LocalLZO PCRE LocalPCRE GNUTLS OPENSSL Sybase DBLib FreeTDS MySQL BerkeleyDB BerkeleyDB++ ODBC PYTHON PYTHON23 PYTHON24 PYTHON25 CPPUNIT Boost.Regex Boost.Spirit Boost.Test Boost.Threads C-Toolkit OpenGL MESA GLUT FLTK wxWindows wxWidgets Fast-CGI SSSUTILS SSSDB SP ORBacus ICU EXPAT SABLOT LIBXML LIBXSLT Xerces Xalan SQLITE SQLITE3 OECHEM JPEG PNG TIFF UNGIF GIF XPM FreeType; do
       case " $WithPackages " in
          *" $x "*) ;;
          *) WithoutPackages="$WithoutPackages$WithoutPackagesSep$x"
@@ -27618,6 +27748,7 @@ eval ncbi_runpath=`echo $pure_runpath`
 
 
 #AC_SUBST(real_srcdir)
+
 
 
 
@@ -28564,6 +28695,8 @@ s,@Z_INCLUDE@,$Z_INCLUDE,;t t
 s,@Z_LIBS@,$Z_LIBS,;t t
 s,@BZ2_INCLUDE@,$BZ2_INCLUDE,;t t
 s,@BZ2_LIBS@,$BZ2_LIBS,;t t
+s,@LZO_INCLUDE@,$LZO_INCLUDE,;t t
+s,@LZO_LIBS@,$LZO_LIBS,;t t
 s,@PCRE_INCLUDE@,$PCRE_INCLUDE,;t t
 s,@PCRE_LIBS@,$PCRE_LIBS,;t t
 s,@GNUTLS_INCLUDE@,$GNUTLS_INCLUDE,;t t
@@ -28710,6 +28843,7 @@ s,@DEMANGLE_LIBS@,$DEMANGLE_LIBS,;t t
 s,@ICONV_LIBS@,$ICONV_LIBS,;t t
 s,@Z_LIB@,$Z_LIB,;t t
 s,@BZ2_LIB@,$BZ2_LIB,;t t
+s,@LZO_LIB@,$LZO_LIB,;t t
 s,@PCREPOSIX_LIBS@,$PCREPOSIX_LIBS,;t t
 s,@PCRE_LIB@,$PCRE_LIB,;t t
 s,@TLS_INCLUDE@,$TLS_INCLUDE,;t t
