Support wxWidgets 2.6.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@25019 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX MT_SFX STATIC LN_S RANLIB ac_ct_RANLIB AR STRIP LORDER TSORT CCACHE TAIL EGREP VALGRIND_PATH CXXCPP AMQ CPP Z_INCLUDE Z_LIBS BZ2_INCLUDE BZ2_LIBS PCRE_INCLUDE PCRE_LIBS FTDS8_INCLUDE FTDS8_LIBS FTDS8_LIB FTDS63_INCLUDE FTDS63_LIBS FTDS63_LIB FTDS_INCLUDE FTDS_LIBS FTDS_LIB freetds ftds8 ftds63 mysql_config X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS EXPAT_INCLUDE EXPAT_LIBS SABLOT_INCLUDE SABLOT_LIBS LIBXML_INCLUDE LIBXML_LIBS LIBXSLT_INCLUDE LIBXSLT_LIBS SQLITE_INCLUDE SQLITE_LIBS OECHEM_INCLUDE OECHEM_LIBS JPEG_INCLUDE JPEG_LIBS PNG_INCLUDE PNG_LIBS TIFF_INCLUDE TIFF_LIBS UNGIF_INCLUDE UNGIF_LIBS GIF_INCLUDE GIF_LIBS XPM_INCLUDE XPM_LIBS freetype_config PROJECTS signature build_root top_srcdir srcdir status_dir builddir runpath ncbi_runpath LINK C_LINK TAIL_N EGREP_Q FAST_CFLAGS FAST_CXXFLAGS DEPFLAGS DEPFLAGS_POST FAST_LDFLAGS C_LIBS GCCPCH D_SFX DEBUG_SFX LIB_OR_DLL FORCE_STATIC_LIB LINK_DLL has_dll_loadable LINK_LOADABLE CFLAGS_DLL CXXFLAGS_DLL OPT_GROUPS local_lbsm ncbi_crypt serial bdb dbapi objects gui algo app internal check CHECK_ARG CHECK_TOOLS script_shell make_shell obj_ext lib_pre lib_l_pre lib_ext dll_ext loadable_ext lib_l_ext exe_ext f_compile f_outobj f_outlib f_libpath f_runpath f_outexe BDB_LIB BDB_CACHE_LIB THREAD_LIBS NETWORK_LIBS NETWORK_PURE_LIBS RESOLVER_LIBS MATH_LIBS KSTAT_LIBS RPCSVC_LIBS CRYPT_LIBS DL_LIBS RT_LIBS ICONV_LIBS Z_LIB BZ2_LIB PCREPOSIX_LIBS PCRE_LIB SYBASE_PATH SYBASE_INCLUDE SYBASE_LIBS SYBASE_DLLS SYBASE_DBLIBS MYSQL_INCLUDE MYSQL_LIBS BERKELEYDB_INCLUDE BERKELEYDB_LIBS BERKELEYDB_STATIC_LIBS BERKELEYDB_CXX_LIBS BERKELEYDB_CXX_STATIC_LIBS ODBC_INCLUDE ODBC_LIBS PYTHON_INCLUDE PYTHON_LIBS CPPUNIT_INCLUDE CPPUNIT_LIBS BOOST_INCLUDE BOOST_LIBPATH BOOST_TAG BOOST_TEST_PEM_LIBS BOOST_TEST_PEM_STATIC_LIBS BOOST_TEST_TEM_LIBS BOOST_TEST_TEM_STATIC_LIBS BOOST_TEST_UTF_LIBS BOOST_TEST_UTF_STATIC_LIBS NCBI_C_INCLUDE NCBI_C_LIBPATH OPENGL_INCLUDE OPENGL_LIBS OSMESA_INCLUDE OSMESA_LIBS GLUT_INCLUDE GLUT_LIBS FLTK_INCLUDE FLTK_LIBS FLTK_LIBS_GL FLTK_LIBS_IMAGES FLTK_LIBS_ALL FLTK_STATIC_LIBS FLTK_STATIC_LIBS_GL FLTK_STATIC_LIBS_IMAGES FLTK_STATIC_LIBS_ALL FLTK_CONFIG WXWIN_INCLUDE WXWIN_LIBS WXWIN_STATIC_LIBS WXWIN_GL_LIBS WXWIN_GL_STATIC_LIBS WXWIN_POST_LINK FASTCGI_INCLUDE FASTCGI_LIBS FASTCGI_OBJS NCBI_SSS_INCLUDE NCBI_SSS_LIBPATH LIBSSSUTILS LIBSSSDB sss ssssrv stax NCBI_GEO_INCLUDE NCBI_GEO_LIBPATH LIBGEODB geo SP_INCLUDE SP_LIBS ORBACUS_INCLUDE ORBACUS_LIBPATH LIBOB LIBIMR ICU_CONFIG ICU_INCLUDE ICU_LIBS ICU_STATIC_LIBS EXPAT_STATIC_LIBS SABLOT_STATIC_LIBS LIBXML_STATIC_LIBS LIBXSLT_STATIC_LIBS XERCES_INCLUDE XERCES_LIBS XERCES_STATIC_LIBS XALAN_INCLUDE XALAN_LIBS XALAN_STATIC_LIBS FREETYPE_INCLUDE FREETYPE_LIBS NCBI_C_ncbi BINCOPY APP_NOCOPY APP_OR_NULL IF_REBUILDING_LIBS IF_REBUILDING_CONDITIONALLY CC_FILTER CXX_FILTER AR_FILTER LINK_FILTER CC_WRAPPER CXX_WRAPPER AR_WRAPPER LINK_WRAPPER KeepStateTarget Rules serial_ws50_rtti_kludge ncbicntr UNIX_SRC UNIX_USR_PROJ compiler compiler_root compiler_version COMPILER OSTYPE NCBI_PLATFORM_BITS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CXX CXXFLAGS ac_ct_CXX MT_SFX STATIC LN_S RANLIB ac_ct_RANLIB AR STRIP LORDER TSORT CCACHE TAIL EGREP VALGRIND_PATH CXXCPP AMQ CPP Z_INCLUDE Z_LIBS BZ2_INCLUDE BZ2_LIBS PCRE_INCLUDE PCRE_LIBS FTDS8_INCLUDE FTDS8_LIBS FTDS8_LIB FTDS63_INCLUDE FTDS63_LIBS FTDS63_LIB FTDS_INCLUDE FTDS_LIBS FTDS_LIB freetds ftds8 ftds63 mysql_config X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS EXPAT_INCLUDE EXPAT_LIBS SABLOT_INCLUDE SABLOT_LIBS LIBXML_INCLUDE LIBXML_LIBS LIBXSLT_INCLUDE LIBXSLT_LIBS SQLITE_INCLUDE SQLITE_LIBS OECHEM_INCLUDE OECHEM_LIBS JPEG_INCLUDE JPEG_LIBS PNG_INCLUDE PNG_LIBS TIFF_INCLUDE TIFF_LIBS UNGIF_INCLUDE UNGIF_LIBS GIF_INCLUDE GIF_LIBS XPM_INCLUDE XPM_LIBS freetype_config PROJECTS signature build_root top_srcdir srcdir status_dir builddir runpath ncbi_runpath LINK C_LINK TAIL_N EGREP_Q FAST_CFLAGS FAST_CXXFLAGS DEPFLAGS DEPFLAGS_POST FAST_LDFLAGS C_LIBS GCCPCH D_SFX DEBUG_SFX LIB_OR_DLL FORCE_STATIC_LIB LINK_DLL has_dll_loadable LINK_LOADABLE CFLAGS_DLL CXXFLAGS_DLL OPT_GROUPS local_lbsm ncbi_crypt serial bdb dbapi objects gui algo app internal check CHECK_ARG CHECK_TOOLS script_shell make_shell obj_ext lib_pre lib_l_pre lib_ext dll_ext loadable_ext lib_l_ext exe_ext f_compile f_outobj f_outlib f_libpath f_runpath f_outexe BDB_LIB BDB_CACHE_LIB THREAD_LIBS NETWORK_LIBS NETWORK_PURE_LIBS RESOLVER_LIBS MATH_LIBS KSTAT_LIBS RPCSVC_LIBS CRYPT_LIBS DL_LIBS RT_LIBS ICONV_LIBS Z_LIB BZ2_LIB PCREPOSIX_LIBS PCRE_LIB SYBASE_PATH SYBASE_INCLUDE SYBASE_LIBS SYBASE_DLLS SYBASE_DBLIBS MYSQL_INCLUDE MYSQL_LIBS BERKELEYDB_INCLUDE BERKELEYDB_LIBS BERKELEYDB_STATIC_LIBS BERKELEYDB_CXX_LIBS BERKELEYDB_CXX_STATIC_LIBS ODBC_INCLUDE ODBC_LIBS PYTHON_INCLUDE PYTHON_LIBS CPPUNIT_INCLUDE CPPUNIT_LIBS BOOST_INCLUDE BOOST_LIBPATH BOOST_TAG BOOST_TEST_PEM_LIBS BOOST_TEST_PEM_STATIC_LIBS BOOST_TEST_TEM_LIBS BOOST_TEST_TEM_STATIC_LIBS BOOST_TEST_UTF_LIBS BOOST_TEST_UTF_STATIC_LIBS NCBI_C_INCLUDE NCBI_C_LIBPATH OPENGL_INCLUDE OPENGL_LIBS OSMESA_INCLUDE OSMESA_LIBS GLUT_INCLUDE GLUT_LIBS FLTK_INCLUDE FLTK_LIBS FLTK_LIBS_GL FLTK_LIBS_IMAGES FLTK_LIBS_ALL FLTK_STATIC_LIBS FLTK_STATIC_LIBS_GL FLTK_STATIC_LIBS_IMAGES FLTK_STATIC_LIBS_ALL FLTK_CONFIG WXWIN_INCLUDE WXWIN_LIBS WXWIN_STATIC_LIBS WXWIN_GL_LIBS WXWIN_GL_STATIC_LIBS WXWIN_POST_LINK WXWIDGETS_INCLUDE WXWIDGETS_LIBS WXWIDGETS_STATIC_LIBS WXWIDGETS_GL_LIBS WXWIDGETS_GL_STATIC_LIBS WXWIDGETS_POST_LINK FASTCGI_INCLUDE FASTCGI_LIBS FASTCGI_OBJS NCBI_SSS_INCLUDE NCBI_SSS_LIBPATH LIBSSSUTILS LIBSSSDB sss ssssrv stax NCBI_GEO_INCLUDE NCBI_GEO_LIBPATH LIBGEODB geo SP_INCLUDE SP_LIBS ORBACUS_INCLUDE ORBACUS_LIBPATH LIBOB LIBIMR ICU_CONFIG ICU_INCLUDE ICU_LIBS ICU_STATIC_LIBS EXPAT_STATIC_LIBS SABLOT_STATIC_LIBS LIBXML_STATIC_LIBS LIBXSLT_STATIC_LIBS XERCES_INCLUDE XERCES_LIBS XERCES_STATIC_LIBS XALAN_INCLUDE XALAN_LIBS XALAN_STATIC_LIBS FREETYPE_INCLUDE FREETYPE_LIBS NCBI_C_ncbi BINCOPY APP_NOCOPY APP_OR_NULL IF_REBUILDING_LIBS IF_REBUILDING_CONDITIONALLY CC_FILTER CXX_FILTER AR_FILTER LINK_FILTER CC_WRAPPER CXX_WRAPPER AR_WRAPPER LINK_WRAPPER KeepStateTarget Rules serial_ws50_rtti_kludge ncbicntr UNIX_SRC UNIX_USR_PROJ compiler compiler_root compiler_version COMPILER OSTYPE NCBI_PLATFORM_BITS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -926,8 +926,10 @@ Optional Packages:
  --with-mesa=DIR         use MESA installation in DIR
  --without-glut          do not use GLUT
  --with-glut=DIR         use GLUT installation in DIR
- --without-wxwin         do not use wxWindows
+ --without-wxwin         do not use wxWindows (2.4-)
  --with-wxwin=DIR        use wxWindows installation in DIR
+ --without-wxwidgets     do not use wxWidgets (2.6+)
+ --with-wxwidgets=DIR    use wxWidgets installation in DIR
  --without-freetype      do not use FreeType
  --with-freetype=DIR     use FreeType installation in DIR
  --without-fastcgi       do not use Fast-CGI library
@@ -1887,6 +1889,18 @@ if test "${with_wxwin2+set}" = set; then
 
 fi;
 
+# Check whether --with-wxwidgets or --without-wxwidgets was given.
+if test "${with_wxwidgets+set}" = set; then
+  withval="$with_wxwidgets"
+
+fi;
+
+# Check whether --with-wxwidgets2 or --without-wxwidgets2 was given.
+if test "${with_wxwidgets2+set}" = set; then
+  withval="$with_wxwidgets2"
+
+fi;
+
 # Check whether --with-freetype or --without-freetype was given.
 if test "${with_freetype+set}" = set; then
   withval="$with_freetype"
@@ -2257,7 +2271,8 @@ x_with_list="\
 debug optimization profiling dll static runpath mt 64 projects ncbi-public \
 exe autodep suffix hostspec execopy bincopy lib-rebuilds lib-rebuilds=ask \
 check static-exe bin-release strip version lfs pch caution \
-ncbi-c wxwin fastcgi sss sssdb sssutils included-sss geo included-geo \
+ncbi-c wxwin wxwidgets fastcgi sss sssdb sssutils included-sss \
+geo included-geo \
 z bz2 pcre sybase sybase-local sybase-new ftds mysql orbacus freetype \
 fltk opengl mesa glut bdb odbc python sqlite icu cppunit boost boost-tag \
 sp expat sablot libxml libxslt xerces xalan oechem gif jpeg tiff png xpm \
@@ -2296,7 +2311,7 @@ echo "$as_me: error: \"  $x_arg:  requires value;  use --help to show usage\"" >
       | --libdir=* | --bindir=* | --includedir=* \
       | [A-Z]*=* \
       | --with-z=* | --with-bz2=* | --with-pcre=* \
-      | --with-sybase-local=* | --with-wxwin=* | --with-orbacus=* \
+      | --with-sybase-local=* | --with-wxwin=* | --with-wxwidgets=* \
       | --with-ftds=* | --with-mysql=* | --with-fltk=* | --with-fastcgi=* \
       | --with-sqlite=* | --with-expat=* | --with-sablot=* \
       | --with-icu=* | --with-xerces=* | --with-xalan=* \
@@ -2304,7 +2319,7 @@ echo "$as_me: error: \"  $x_arg:  requires value;  use --help to show usage\"" >
       | --with-python=* | --with-freetype=* | --with-gif=* | --with-jpeg=* \
       | --with-png=* | --with-tiff=* | --with-xpm=* | --with-opengl=* \
       | --with-mesa=* | --with-glut=* | --with-oechem=* | --with-cppunit=* \
-      | --with-boost=* | --with-boost-tag=* \
+      | --with-boost=* | --with-boost-tag=* | --with-orbacus=* \
       | --target=* | --with-runpath=* | --no-create | --no-recursion)
       ;;
 
@@ -21454,6 +21469,153 @@ _ACEOF
 fi
 
 
+## wxWidgets
+if test "$with_wxwidgets" != "no" ; then
+   if test -z "$WXWIDGETS_PATH"; then
+      if test -d "$with_wxwidgets"; then
+         WXWIDGETS_PATH=$with_wxwidgets
+      else
+         WXWIDGETS_PATH="$NCBI/wxwidgets"
+      fi
+   fi
+   if test -d "$WXWIDGETS_PATH/${compiler_vpfx}${DEBUG_SFX}${mt_sfx}${bit64_sfx}/lib" \
+        -a -z "$WXWIDGETS_ARCH_PATH"; then
+      WXWIDGETS_ARCH_PATH="$WXWIDGETS_PATH/${compiler_vpfx}${DEBUG_SFX}${mt_sfx}${bit64_sfx}"
+   elif test -d "$WXWIDGETS_PATH/${compiler_pfx}${DEBUG_SFX}${mt_sfx}${bit64_sfx}/lib" \
+        -a -z "$WXWIDGETS_ARCH_PATH"; then
+      WXWIDGETS_ARCH_PATH="$WXWIDGETS_PATH/${compiler_pfx}${DEBUG_SFX}${mt_sfx}${bit64_sfx}"
+   else
+      WXWIDGETS_ARCH_PATH="$WXWIDGETS_PATH"
+   fi
+   WXWIDGETS_BINPATH=${WXWIDGETS_BINPATH:="$WXWIDGETS_ARCH_PATH/bin"}
+   WXWIDGETS_LIBPATH=${WXWIDGETS_LIBPATH:="$WXWIDGETS_ARCH_PATH/lib"}
+   WXWIDGETS_INCLUDE=
+   wxconf=$WXWIDGETS_BINPATH/wx-config
+   for x in `"$wxconf" --libs --static`; do
+      case "$x" in
+         -L*)
+             d=`echo $x | sed -e 's/^-L//'`
+             pcd=$d/pkgconfig
+             if test -d "$pcd"; then
+                PKG_CONFIG_PATH="${PKG_CONFIG_PATH+$PKG_CONFIG_PATH:}$pcd"
+             fi
+             ;;
+      esac
+   done
+   export PKG_CONFIG_PATH
+   if "$wxconf" --list | grep 'Default config is gtk2' >/dev/null; then
+      gtkconf="pkg-config gtk+-2.0"
+   elif test -x "$WXWIDGETS_BINPATH/gtk-config"; then
+      gtkconf=$WXWIDGETS_BINPATH/gtk-config
+   elif gtk-config --version >/dev/null 2>&1; then
+      gtkconf=gtk-config
+   else
+      # May work without gtk-config (e.g., on Mac OS X)
+      gtkconf=:
+   fi
+   case "$host_os" in
+      darwin* ) baseflags=""                  ;;
+      *       ) baseflags=`$gtkconf --cflags` ;;
+   esac
+   echo "$as_me:$LINENO: checking for wxWidgets in $WXWIDGETS_ARCH_PATH" >&5
+echo $ECHO_N "checking for wxWidgets in $WXWIDGETS_ARCH_PATH... $ECHO_C" >&6
+if test "${ncbi_cv_lib_wxwidgets+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -x "$wxconf" ; then
+          WXWIDGETS_INCLUDE="$baseflags `$wxconf --cflags`"
+          WXWIDGETS_LIBS=`$wxconf --libs |\
+             sed -e "s/-L\\([^ ]*\\)/-L\\1 ${CONF_f_runpath}\\1/"`
+
+          CPPFLAGS="$WXWIDGETS_INCLUDE $orig_CPPFLAGS"
+          LIBS="$WXWIDGETS_LIBS $orig_LIBS"
+          cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <wx/wx.h>
+int
+main ()
+{
+ wxExit();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_lib_wxwidgets=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ncbi_cv_lib_wxwidgets=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+       else
+          ncbi_cv_lib_wxwidgets=no
+       fi
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_lib_wxwidgets" >&5
+echo "${ECHO_T}$ncbi_cv_lib_wxwidgets" >&6
+   if test "$ncbi_cv_lib_wxwidgets" = "no"; then
+      with_wxwidgets="no"
+   fi
+fi
+
+if test "$with_wxwidgets" = "no" ; then
+   WXWIDGETS_LIBPATH="No_wxWidgets"
+   WXWIDGETS_INCLUDE=
+   WXWIDGETS_LIBS=
+   WXWIDGETS_STATIC_LIBS=
+   WXWIDGETS_GL_LIBS=
+   WXWIDGETS_GL_STATIC_LIBS=
+   WXWIDGETS_POST_LINK=:
+   WithoutPackages="$WithoutPackages wxWidgets"
+else
+   WithPackages="$WithPackages wxWidgets"
+   # The "yes" may have been cached; get the actual settings again if needed
+   if test -z "$WXWIDGETS_INCLUDE"; then
+      WXWIDGETS_INCLUDE="$baseflags `$wxconf --cflags`"
+      WXWIDGETS_LIBS=`$wxconf --libs |\
+         sed -e "s/-L\\([^ ]*\\)/-L\\1 ${CONF_f_runpath}\\1/"`
+   fi
+   WXWIDGETS_STATIC_LIBS=`$wxconf --libs --static`
+   WXWIDGETS_GL_LIBS=`$wxconf --gl-libs`
+   WXWIDGETS_GL_STATIC_LIBS=`$wxconf --gl-libs --static`
+   WXWIDGETS_POST_LINK=`$wxconf --rezflags`
+   test -n "$WXWIDGETS_POST_LINK"  ||  WXWIDGETS_POST_LINK=:
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_WXWIDGETS 1
+_ACEOF
+
+fi
+
+
 ## In-house Fast-CGI library
 if test "$with_fastcgi" != "no" ; then
    case "$with_fastcgi" in
@@ -24690,6 +24852,12 @@ eval ncbi_runpath=`echo $pure_runpath`
 
 
 
+
+
+
+
+
+
 #############################################################################
 ### Create output files and do some post-configuration
 
@@ -25576,6 +25744,12 @@ s,@WXWIN_STATIC_LIBS@,$WXWIN_STATIC_LIBS,;t t
 s,@WXWIN_GL_LIBS@,$WXWIN_GL_LIBS,;t t
 s,@WXWIN_GL_STATIC_LIBS@,$WXWIN_GL_STATIC_LIBS,;t t
 s,@WXWIN_POST_LINK@,$WXWIN_POST_LINK,;t t
+s,@WXWIDGETS_INCLUDE@,$WXWIDGETS_INCLUDE,;t t
+s,@WXWIDGETS_LIBS@,$WXWIDGETS_LIBS,;t t
+s,@WXWIDGETS_STATIC_LIBS@,$WXWIDGETS_STATIC_LIBS,;t t
+s,@WXWIDGETS_GL_LIBS@,$WXWIDGETS_GL_LIBS,;t t
+s,@WXWIDGETS_GL_STATIC_LIBS@,$WXWIDGETS_GL_STATIC_LIBS,;t t
+s,@WXWIDGETS_POST_LINK@,$WXWIDGETS_POST_LINK,;t t
 s,@FASTCGI_INCLUDE@,$FASTCGI_INCLUDE,;t t
 s,@FASTCGI_LIBS@,$FASTCGI_LIBS,;t t
 s,@FASTCGI_OBJS@,$FASTCGI_OBJS,;t t
