Treat all letters as lowercase for case-insensitive comparisons.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@18011 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8487,6 +8487,69 @@ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ex
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 
+# We want the program to return 0, which is *false* in C.  Also, since
+# use of lowercase seems to be customary if not universal, the default
+# is yes when cross-compiling; anyone cross-compiling for exceptional
+# platforms can set ncbi_cv_func_strcasecmp_lc=no in config.site.
+if test "$ac_cv_func_strcasecmp" = yes; then
+   echo "$as_me:$LINENO: checking whether strcasecmp treats letters as lowercase" >&5
+echo $ECHO_N "checking whether strcasecmp treats letters as lowercase... $ECHO_C" >&6
+if test "${ncbi_cv_func_strcasecmp_lc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  ncbi_cv_func_strcasecmp_lc=yes
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <string.h>
+int
+main ()
+{
+return strcasecmp("A", "_") <= 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_func_strcasecmp_lc=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+ncbi_cv_func_strcasecmp_lc=no
+fi
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_func_strcasecmp_lc" >&5
+echo "${ECHO_T}$ncbi_cv_func_strcasecmp_lc" >&6
+   if test "$ncbi_cv_func_strcasecmp_lc" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STRCASECMP_LC 1
+_ACEOF
+
+   fi
+fi
+
 echo "$as_me:$LINENO: checking for Linux-like sysinfo with 1 arg" >&5
 echo $ECHO_N "checking for Linux-like sysinfo with 1 arg... $ECHO_C" >&6
 if test "${ncbi_cv_func_sysinfo_1+set}" = set; then
