Check whether unaligned reads are permissible.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@33412 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17378,6 +17378,66 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking whether unaligned reads are permissible" >&5
+echo $ECHO_N "checking whether unaligned reads are permissible... $ECHO_C" >&6
+if test "${ncbi_cv_sys_unaligned_reads+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  case "$host_cpu" in
+          i?86|x86_64|powerpc*|ppc*) ncbi_cv_sys_unaligned_reads=yes ;;
+          *)                         ncbi_cv_sys_unaligned_reads=no  ;;
+        esac
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <stdio.h>
+int
+main ()
+{
+ unsigned int a[2] = { 0x01234567, 0x89abcdef };
+          fprintf(stderr, "%x\n", *(unsigned int*)((char*)a + 1));
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_sys_unaligned_reads=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+ncbi_cv_sys_unaligned_reads=no
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_sys_unaligned_reads" >&5
+echo "${ECHO_T}$ncbi_cv_sys_unaligned_reads" >&6
+if test "$ncbi_cv_sys_unaligned_reads" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_UNALIGNED_READS 1
+_ACEOF
+
+fi
+
 ### Check for the availability of other packages
 ### --------------------------------------------
 
