Assess select's timeout handling; support BDB 4.4.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@27433 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9954,8 +9954,9 @@ done
 
 
 
+
 for ac_func in atoll lchown getpagesize getpwuid gettimeofday getuid \
-               nanosleep asprintf vasprintf vsnprintf statfs statvfs \
+               nanosleep asprintf vasprintf vsnprintf select statfs statvfs \
                strcasecmp strdup strndup strtok_r sysmp timegm utimes lutimes
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -10063,6 +10064,150 @@ ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
+
+echo "$as_me:$LINENO: checking return type of signal handlers" >&5
+echo $ECHO_N "checking return type of signal handlers... $ECHO_C" >&6
+if test "${ac_cv_type_signal+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/types.h>
+#include <signal.h>
+#ifdef signal
+# undef signal
+#endif
+#ifdef __cplusplus
+extern "C" void (*signal (int, void (*)(int)))(int);
+#else
+void (*signal ()) ();
+#endif
+
+int
+main ()
+{
+int i;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_signal=void
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_type_signal=int
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_signal" >&5
+echo "${ECHO_T}$ac_cv_type_signal" >&6
+
+cat >>confdefs.h <<_ACEOF
+#define RETSIGTYPE $ac_cv_type_signal
+_ACEOF
+
+
+test "$ac_cv_func_select" = yes  ||  ncbi_cv_func_select_updates_timeout=no
+echo "$as_me:$LINENO: checking whether select updates the timeout when interrupted" >&5
+echo $ECHO_N "checking whether select updates the timeout when interrupted... $ECHO_C" >&6
+if test "${ncbi_cv_func_select_updates_timeout+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  case "$host_os" in
+          linux) ncbi_cv_func_select_updates_timeout=yes ;;
+	  *) ncbi_cv_func_select_updates_timeout=no ;;
+	esac
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <signal.h>
+	 #include <sys/types.h>
+         #ifdef HAVE_SYS_SELECT_H
+         #  include <sys/select.h>
+	 #endif
+	 #ifdef HAVE_SYS_TIME_H
+	 #  include <sys/time.h>
+	 #endif
+	 #ifdef HAVE_UNISTD_H
+	 #  include <unistd.h>
+	 #endif
+         RETSIGTYPE handler(int sig) { }
+int
+main ()
+{
+struct timeval timeout = { 5, 0 };
+         signal(SIGALRM, &handler);
+         alarm(1);
+	 select(0, NULL, NULL, NULL, &timeout);
+	 return timeout.tv_sec == 5;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_func_select_updates_timeout=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+ncbi_cv_func_select_updates_timeout=no
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_func_select_updates_timeout" >&5
+echo "${ECHO_T}$ncbi_cv_func_select_updates_timeout" >&6
+if test "$ncbi_cv_func_select_updates_timeout" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define SELECT_UPDATES_TIMEOUT 1
+_ACEOF
+
+fi
 
 # We want the program to return 0, which is *false* in C.  Also, since
 # use of lowercase seems to be customary if not universal, the default
@@ -19022,7 +19167,7 @@ echo "${ECHO_T}$ncbi_cv_lib_berkeley_db_version" >&6
 echo "$as_me: WARNING: Your Berkeley DB version is too old to use.  (Needed 4.3.)" >&2;}
             with_bdb=no
             ;;
-         4.3.* ) ;;
+         4.3.* | 4.4.* ) ;;
          * )
             { echo "$as_me:$LINENO: WARNING: Untested Berkeley DB version; may prove incompatible." >&5
 echo "$as_me: WARNING: Untested Berkeley DB version; may prove incompatible." >&2;}
