Tweak profiling support per Mike DiCuccio's suggestions.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@6966 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3755,6 +3755,21 @@ else
    pure_runpath=
 fi
 
+# DLLs and profiling don't mix on all platforms
+if test "$with_profiling" = "yes" ; then
+   case "$host_os" in
+      linux*) # any others?
+         case "$with_dll" in
+            yes) { { echo "$as_me:$LINENO: error: This platform does not support DLL profiling." >&5
+echo "$as_me: error: This platform does not support DLL profiling." >&2;}
+   { (exit 1); exit 1; }; }
+                 ;;
+	    no) ;;
+            *) with_dll=no ;;
+         esac
+      ;;
+   esac
+fi
 
 # Whether to build DLLs or static (and whether by default, or forcibly)
 LIB_OR_DLL="lib"
@@ -4188,7 +4203,7 @@ if test "$with_profiling" = "yes" ; then
    prof_sfx="Prof"
    case "$compiler" in
       Compaq)    PFFLAGS="-pg" ;;
-      GCC)       PFFLAGS="-pg -ax" ;;
+      GCC)       PFFLAGS="-pg -fprofile-arcs" ;;
       ICC)       PFFLAGS="-p" ;;
       KCC)       PFFLAGS="-pg" ;;
       MIPSpro73) PFFLAGS="" ;; # pixie(1) adds info at runtime
@@ -4200,6 +4215,7 @@ if test "$with_profiling" = "yes" ; then
    CFLAGS="$CFLAGS $PFFLAGS"
    CXXFLAGS="$CXXFLAGS $PFFLAGS"
    LDFLAGS="$LDFLAGS $PFFLAGS"
+   STRIP=: # Stripping may lose profiling info
 else
    prof_sfx=
 fi
