When compiling with GCC or ICC, always check whether the linker supports [-Wl,]-E (a GNU-specific option) and supply it if so.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@27765 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4258,6 +4258,68 @@ CFLAGS="$MT_FLAG $CFLAGS"
 CXXFLAGS="$MT_FLAG $CXXFLAGS"
 LDFLAGS="$MT_FLAG $LDFLAGS"
 
+case "$compiler" in
+   GCC | ICC )
+      orig_LDFLAGS=$LDFLAGS
+      LDFLAGS="-Wl,-E $LDFLAGS"
+
+echo "$as_me:$LINENO: checking whether $CC supports -Wl,-E" >&5
+echo $ECHO_N "checking whether $CC supports -Wl,-E... $ECHO_C" >&6
+if test "${ncbi_cv_prog_cc_wl_e+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_prog_cc_wl_e=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ncbi_cv_prog_cc_wl_e=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_prog_cc_wl_e" >&5
+echo "${ECHO_T}$ncbi_cv_prog_cc_wl_e" >&6
+      test "$ncbi_cv_prog_cc_wl_e" = yes  ||  LDFLAGS=$orig_LDFLAGS
+      ;;
+esac
 
 #### Provide default environment setup for known platforms/compilers
 DEPFLAGS="-M"
@@ -4273,19 +4335,10 @@ case "$host_os:$compiler" in
    STRIP="@:"
    ;;
 
- linux*:GCC )
-   LDFLAGS="-Wl,-E $LDFLAGS"
-   ;;
-
  linux*:ICC )
-   LDFLAGS="-Wl,-E $LDFLAGS"
    # "incomplete type is not allowed" should be an error, not a warning!
    CFLAGS="-we70 $CFLAGS"
    CXXFLAGS="-we70 $CXXFLAGS"
-   ;;
-
- freebsd*:GCC )
-   LDFLAGS="-Wl,-E $LDFLAGS"
    ;;
 
  irix*:GCC )
@@ -4590,8 +4643,7 @@ LIBS="$MATH_LIBS $LIBS"
 C_LIBS="$MATH_LIBS $C_LIBS"
 
 if test -n "$with_64"; then
-
-echo "$as_me:$LINENO: checking whether this system supports --with(out)-64" >&5
+   echo "$as_me:$LINENO: checking whether this system supports --with(out)-64" >&5
 echo $ECHO_N "checking whether this system supports --with(out)-64... $ECHO_C" >&6
 if test "${ncbi_cv_sys_with64_ok+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
