Add a (relatively thorough) check for getlogin_r().
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@26430 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4157,7 +4157,7 @@ compiler_root=`echo $CXX | sed -ne 's:\(.*\)[/\\]bin[/\\].*:\1:p'`
 with_mt=${with_mt:="no"}
 if test "$with_mt" = "yes" ; then
    case "$host_os:$compiler" in
-    darwin* | irix*          )  ;;
+    darwin* | irix* | cygwin*)  ;;
     solaris*:WorkShop*       )  : ${MT_FLAG:="-mt"} ;;
     solaris*:GCC             )  : ${MT_FLAG:="-pthreads"} ;;
     *:KCC                    )  : ${MT_FLAG:="--thread_safe"} ;;
@@ -9258,6 +9258,68 @@ _ACEOF
 
 fi
 
+# Perform a full-fledged check in C++ to be sure of an actual declaration.
+echo "$as_me:$LINENO: checking for getlogin_r" >&5
+echo $ECHO_N "checking for getlogin_r... $ECHO_C" >&6
+if test "${ncbi_cv_func_getlogin_r+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ncbi_cv_func_getlogin_r="no"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <unistd.h>
+int
+main ()
+{
+char buf[64]; return getlogin_r(buf, 64);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_func_getlogin_r=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ncbi_cv_func_getlogin_r=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_func_getlogin_r" >&5
+echo "${ECHO_T}$ncbi_cv_func_getlogin_r" >&6
+if test $ncbi_cv_func_getlogin_r = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_GETLOGIN_R 1
+_ACEOF
+
+fi
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -19205,6 +19267,10 @@ echo $ECHO_N "checking for Boost library name tag... $ECHO_C" >&6
                *       ) BOOST_TAG="${BOOST_TAG}-mt" ;;
             esac
          fi
+         case "$BOOST_TAG" in
+            *-mt) ;;
+            *) BOOST_INCLUDE="$BOOST_INCLUDE -DBOOST_DISABLE_THREADS" ;;
+         esac
          test "$with_debug" = "no"   ||  BOOST_TAG="${BOOST_TAG}-d"
          BOOST_TAG="${BOOST_TAG}-${ncbi_cv_lib_boost_version}"
          test "$bit64_sfx"  = "64"   &&  BOOST_TAG="${BOOST_TAG}-64"
