Rearrange so as to play better with import_project.sh and generally reduce confusion; in particular, fold Makefile into Makefile.sources. JIRA: CXX-60
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@35839 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/objects/Makefile.sources b/src/objects/Makefile.sources
--- a/src/objects/Makefile.sources
+++ b/src/objects/Makefile.sources
@@ -2,9 +2,49 @@
 #
 # Generate ASN.1 serialization code in the "objects/" projects
 
+# Default directory settings, corresponding to an import_project.sh-
+# produced layout; normal builds will override these on the command line.
+builddir = ..
+srcdir   = .
+
 include $(builddir)/Makefile.mk
 
-all all_r all_p:
-	cd "$(srcdir)" || exit 2; $(MAKE) all_files
+MODULES = omssa access biblio blast blastdb blastxml cdd cn3d docsum biotree \
+          entrez2 entrezgene featdef gbseq general id1 id2 insdseq \
+          medlars medline mim mla mmdb1 mmdb2 mmdb3 ncbimime objprt \
+          proj pub pubmed scoremat seq seqalign seqblock seqcode \
+          seqfeat seqloc seqsplit seqres seqset submit taxon1 tinyseq \
+          pcsubstance pcassay remap homologene seqedit seqtable seqtest valerr
+
+new_module = $(builddir)/new_module.sh
+
+all all_files sources makefiles directories purge_sources purge_all_sources purge_all_files:
+	cd $(srcdir) || exit 2; \
+	for i in $(MODULES); do \
+	  if test -f "$$i/$$i.asn"; then \
+	    MAKE=$(MAKE); export MAKE; \
+	    ( cd $$i && $(new_module) $$i $@; ) \
+	    || case "$(MFLAGS)" in *k*) ;; *) exit 2 ;; esac; \
+	  else \
+	    echo "Warning: $$i/$$i.asn not found (skipping)"; \
+	  fi; \
+	done
+
+all_r all_p: all
+
+refresh: clean_sources
+	$(MAKE) all
+
+clean_sources:
+	for i in $(MODULES); do \
+	    rm -f $(srcdir)/$$i/$$i.files; \
+	done
+
+ASNFILES = $(MODULES:%=$(srcdir)/%/%.asn)
+
+$(srcdir)/all.asn: $(ASNFILES)
+	cat $(ASNFILES) >$@
+
+all.asn: $(srcdir)/all.asn
 
 clean clean_r clean_p purge purge_r purge_p:
