return nothing on success. All output is on errout.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@12198 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/compilers/mac_prj/makesqlite b/compilers/mac_prj/makesqlite
--- a/compilers/mac_prj/makesqlite
+++ b/compilers/mac_prj/makesqlite
@@ -1,5 +1,5 @@
 #! /bin/sh
-# $Id: makesqlite,v 1.1 2003/10/29 14:22:52 rsmith Exp $
+# $Id: makesqlite,v 1.2 2003/11/20 18:01:48 rsmith Exp $
 
 sqlitedir=${1:-sqlite}
 sqlitebuilddir=${2:-${sqlitedir}-build}
@@ -13,13 +13,12 @@ fi
 cd ${sqlitebuilddir}
 
 # NO, metrowerks compiler does not work for this.
-#export CC=mwcc
+# export CC=mwcc
 # export CFLAGS=-char unsigned
 
 {
+ # echo "Error test: Oh, wretched failure! "; echo "Alack, alay!"; exit 1;
  { echo '** Configure'; ${sqlitedir}/configure -prefix=${sqliteinstalldir} ; } && \
  { echo '** Compile'; make all ; } && \
  { echo '** Install'; make install ; }
 } >&2
-
-echo $sqliteinstalldir
