configure(.ac): Acknowledge two more gbench requirements: Boost.Spirit (for the HGVS parser) and libxslt.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@74740 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -4251,6 +4251,20 @@ echo "$as_me: error: incompatible options: --without-bdb but --with-gbench" >&2;
       else
          : ${with_bdb:=yes}
       fi
+     if test "$with_boost" = "no"; then
+         { { echo "$as_me:$LINENO: error: incompatible options: --without-boost but --with-gbench" >&5
+echo "$as_me: error: incompatible options: --without-boost but --with-gbench" >&2;}
+   { (exit 1); exit 1; }; }
+      else
+         : ${with_boost:=yes}
+      fi
+     if test "$with_xslt" = "no"; then
+         { { echo "$as_me:$LINENO: error: incompatible options: --without-xslt but --with-gbench" >&5
+echo "$as_me: error: incompatible options: --without-xslt but --with-gbench" >&2;}
+   { (exit 1); exit 1; }; }
+      else
+         : ${with_xslt:=yes}
+      fi
 
    : ${with_projects=scripts/projects/ncbi_gbench.lst}
 elif test "$with_jni" = "yes" ; then
@@ -46519,6 +46533,10 @@ if test "$with_gbench" != "no"  -a  -d "$real_srcdir/src/app/gbench"; then
    fi
    if test "$with_bdb" = "no"; then
      reason="$reason${sep}Berkeley DB"
+     sep=", "
+   fi
+   if test "$ncbi_cv_lib_boost_spirit" != "yes"; then
+     reason=Boost.Spirit
      sep=", "
    fi
    if test "$with_mt" = "no"; then
