configure(.ac): Have --with-gbench merely imply --with-glew rather than insisting on --with-glew-mx.  JIRA: GB-7199.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@78794 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -4378,12 +4378,12 @@ echo "$as_me: error: incompatible options: --without-algo but --with-gbench" >&2
       else
          : ${with_algo:=yes}
       fi
-     if test "$with_glew_mx" = "no"; then
-         { { echo "$as_me:$LINENO: error: incompatible options: --without-glew_mx but --with-gbench" >&5
-echo "$as_me: error: incompatible options: --without-glew_mx but --with-gbench" >&2;}
+     if test "$with_glew" = "no"; then
+         { { echo "$as_me:$LINENO: error: incompatible options: --without-glew but --with-gbench" >&5
+echo "$as_me: error: incompatible options: --without-glew but --with-gbench" >&2;}
    { (exit 1); exit 1; }; }
       else
-         : ${with_glew_mx:=yes}
+         : ${with_glew:=yes}
       fi
      if test "$with_wxwidgets" = "no"; then
          { { echo "$as_me:$LINENO: error: incompatible options: --without-wxwidgets but --with-gbench" >&5
@@ -48649,8 +48649,8 @@ if test "$with_gbench" != "no"  -a  -d "$real_srcdir/src/app/gbench"; then
      reason="$reason${sep}OpenGL"
      sep=", "
    fi
-   if test "$with_glew_mx" = "no"; then
-     reason="$reason${sep}GLEWmx"
+   if test "$with_glew" = "no"; then
+     reason="$reason${sep}GLEW"
      sep=", "
    fi
    if test "$with_ftgl" = "no"; then
