When building with GCC or ICC, pass --enable-new-dtags to the linker if it supports that option, to ensure that users who need to override compiled-in runpaths can do so via LD_LIBRARY_PATH.  JIRA: SYS-121923.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@49312 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -4975,6 +4975,65 @@ fi
 echo "$as_me:$LINENO: result: $ncbi_cv_prog_cc_wl_e" >&5
 echo "${ECHO_T}$ncbi_cv_prog_cc_wl_e" >&6
       test "$ncbi_cv_prog_cc_wl_e" = no  ||  APP_LDFLAGS="-Wl,-E $APP_LDFLAGS"
+      echo "$as_me:$LINENO: checking whether $CC supports -Wl,--enable-new-dtags" >&5
+echo $ECHO_N "checking whether $CC supports -Wl,--enable-new-dtags... $ECHO_C" >&6
+if test "${ncbi_cv_prog_cc_new_dtags+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  orig_LDFLAGS=$LDFLAGS
+          LDFLAGS="-Wl,--enable-new-dtags $LDFLAGS"
+          cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_prog_cc_new_dtags=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ncbi_cv_prog_cc_new_dtags=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+          LDFLAGS=$orig_LDFLAGS
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_prog_cc_new_dtags" >&5
+echo "${ECHO_T}$ncbi_cv_prog_cc_new_dtags" >&6
+      test "$ncbi_cv_prog_cc_new_dtags" = no \
+          ||  LDFLAGS="-Wl,--enable-new-dtags $LDFLAGS"
       ;;
 esac
 
