Check for the NCBI NGS SDK.  JIRA: CXX-11063.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@88570 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -799,6 +799,8 @@ LIBEXSLT_INCLUDE
 LIBEXSLT_LIBS
 SQLITE3_INCLUDE
 SQLITE3_LIBS
+NGS_INCLUDE
+NGS_LIBS
 OECHEM_INCLUDE
 OECHEM_LIBS
 SGE_INCLUDE
@@ -1067,6 +1069,7 @@ ncbi_xloader_vdbgraph
 ncbi_xloader_wgs
 VDB_REQ
 VDB_POST_LINK
+NGS_STATIC_LIBS
 SP_INCLUDE
 SP_LIBS
 ORBACUS_INCLUDE
@@ -1679,8 +1682,8 @@ autodep suffix hostspec version execopy bincopy lib-rebuilds lib-rebuilds=ask \
 deactivation makefile-auto-update projects flat-makefile configure-dialog \
 check ncbi-public strip pch caution ccache distcc \
 ncbi-c wxwidgets wxwidgets-ucs fastcgi sss sssdb sssutils included-sss \
-geo included-geo vdb downloaded-vdb static-vdb libunwind libdw backward-cpp \
-backward-cpp-sig \
+geo included-geo vdb downloaded-vdb static-vdb ngs libunwind libdw \
+backward-cpp backward-cpp-sig \
 z bz2 lzo pcre mbedtls gmp gcrypt nettle gnutls static-gnutls openssl krb5 \
 sybase sybase-local sybase-new ftds mysql \
 orbacus freetype ftgl opengl mesa glut glew glew-mx gl2ps \
@@ -1745,8 +1748,8 @@ for x_arg in "$@" ; do
       --with-vdb=rc ) ;;
 
       --srcdir=* | --x-includes=* | --x-libraries=* | --with-tcheck=* \
-      | --with-ncbi-c=* | --with-sss=* | --with-vdb=* | --with-libunwind=* \
-      | --with-libdw=* | --with-backward-cpp=* \
+      | --with-ncbi-c=* | --with-sss=* | --with-vdb=* | --with-ngs=* \
+      | --with-libunwind=* | --with-libdw=* | --with-backward-cpp=* \
       | --with-z=* | --with-bz2=* | --with-lzo=* \
       | --with-pcre=* | --with-mbedtls=* \
       | --with-gmp=* | --with-gcrypt=* | --with-nettle=* \
@@ -1965,6 +1968,8 @@ Optional Packages:
  --without-vdb           do not use the NCBI SRA/VDB Toolkit
  --with-downloaded-vdb   download and build SRA/VDB from GitHub
  --with-static-vdb       always link statically against SRA/VDB
+ --with-ngs=DIR          use NCBI NGS SDK installation in DIR
+ --without-ngs           do not use the NCBI NGS SDK
  --with-libunwind(=DIR)  use libunwind (in DIR)
  --with-libdw=DIR        use elfutils libdw installation in DIR
  --without-libdw         do not use elfutils libdw
@@ -2314,6 +2319,12 @@ case "$with_3psw" in
    { (exit 1); exit 1; }; }
          else
             with_vdb=no
+         fi
+        if test "${with_ngs-no}" != "no"; then
+            { echo "$as_me: error: incompatible options: --with-ngs but --without-3psw" >&2
+   { (exit 1); exit 1; }; }
+         else
+            with_ngs=no
          fi
         if test "${with_libunwind-no}" != "no"; then
             { echo "$as_me: error: incompatible options: --with-libunwind but --without-3psw" >&2
@@ -3543,6 +3554,18 @@ fi
 # Check whether --with-static-vdb was given.
 if test "${with_static_vdb+set}" = set; then
   withval=$with_static_vdb;
+fi
+
+
+# Check whether --with-ngs was given.
+if test "${with_ngs+set}" = set; then
+  withval=$with_ngs;
+fi
+
+
+# Check whether --with-ngs was given.
+if test "${with_ngs+set}" = set; then
+  withval=$with_ngs;
 fi
 
 
@@ -44969,6 +44992,261 @@ _ACEOF
 echo "$as_me: error: --with-vdb explicitly specified, but no usable version found." >&2;}
    { (exit 1); exit 1; }; }
     fi
+      if test "${with_ngs:=no}" != no; then
+       { { echo "$as_me:$LINENO: error: --with-ngs explicitly specified, but no usable version found." >&5
+echo "$as_me: error: --with-ngs explicitly specified, but no usable version found." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+   fi
+else
+   if test "${with_ngs:=no}" != no; then
+       { { echo "$as_me:$LINENO: error: --with-ngs explicitly specified, but no usable version found." >&5
+echo "$as_me: error: --with-ngs explicitly specified, but no usable version found." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+fi
+
+
+### NCBI NGS SDK
+if test "$with_ngs" != "no" ; then
+   if test "${with_ngs:-yes}" != "yes" -a -d "$with_ngs"; then
+      NGS_PATH=$with_ngs
+   fi
+   NGS_INCLUDE="-I$NGS_PATH/include"
+   case "$host_cpu:$bit64_sfx" in
+      *86*:64 ) extra_inc="-I$NGS_PATH/include/ngs/unix/x86_64" ;;
+      *86*:*  ) extra_inc="-I$NGS_PATH/include/ngs/unix/fat86"  ;;
+      *       ) extra_inc=''                                    ;;
+   esac
+   CPPFLAGS="$VDB_INCLUDE $orig_CPPFLAGS"
+   for x in "$vdb_libpath" "lib${bit64_sfx:-32}" lib; do
+      if test -n "$x" -a -d "$NGS_PATH/$x"; then
+         : ${NGS_LIBDIR=$NGS_PATH/$x}
+         break
+      fi
+   done
+   ncbi_rp_L_flags=
+ ncbi_rp_L_sep=$CONF_f_libpath
+ if test "x${CONF_f_runpath}" = "x${CONF_f_libpath}"; then
+    for x in $NGS_LIBDIR; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+    done
+    NGS_LIBPATH="${ncbi_rp_L_flags}"
+ else
+    ncbi_rp_R_flags=
+    ncbi_rp_R_sep=" $CONF_f_runpath"
+    for x in $NGS_LIBDIR; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+       x=`echo $x | sed -e "$ncbi_rpath_sed"`
+       ncbi_rp_R_flags="${ncbi_rp_R_flags}${ncbi_rp_R_sep}$x"
+       ncbi_rp_R_sep=:
+    done
+    NGS_LIBPATH="${ncbi_rp_L_flags}${ncbi_rp_R_flags}"
+ fi
+   if test "$with_ngs" != "no"; then
+    case "$NGS_PATH:$with_ngs" in
+       *:yes | *: | $with_ngs* ) ;;
+       * ) NGS_PATH=$with_ngs ;;
+    esac
+    if test "$NGS_PATH" != /usr -a -d "$NGS_PATH"; then
+       in_path=" in $NGS_PATH"
+       if test -z "$NGS_INCLUDE" -a -d "$NGS_PATH/include"; then
+          NGS_INCLUDE="-I$NGS_PATH/include"
+       fi
+       if test -n "$NGS_LIBPATH"; then
+          :
+       elif test -d "$NGS_PATH/lib${bit64_sfx}"; then
+          ncbi_rp_L_flags=
+ ncbi_rp_L_sep=$CONF_f_libpath
+ if test "x${CONF_f_runpath}" = "x${CONF_f_libpath}"; then
+    for x in $NGS_PATH/lib${bit64_sfx}; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+    done
+    NGS_LIBPATH="${ncbi_rp_L_flags}"
+ else
+    ncbi_rp_R_flags=
+    ncbi_rp_R_sep=" $CONF_f_runpath"
+    for x in $NGS_PATH/lib${bit64_sfx}; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+       x=`echo $x | sed -e "$ncbi_rpath_sed"`
+       ncbi_rp_R_flags="${ncbi_rp_R_flags}${ncbi_rp_R_sep}$x"
+       ncbi_rp_R_sep=:
+    done
+    NGS_LIBPATH="${ncbi_rp_L_flags}${ncbi_rp_R_flags}"
+ fi
+       elif test -d "$NGS_PATH/lib"; then
+          ncbi_rp_L_flags=
+ ncbi_rp_L_sep=$CONF_f_libpath
+ if test "x${CONF_f_runpath}" = "x${CONF_f_libpath}"; then
+    for x in $NGS_PATH/lib; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+    done
+    NGS_LIBPATH="${ncbi_rp_L_flags}"
+ else
+    ncbi_rp_R_flags=
+    ncbi_rp_R_sep=" $CONF_f_runpath"
+    for x in $NGS_PATH/lib; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+       x=`echo $x | sed -e "$ncbi_rpath_sed"`
+       ncbi_rp_R_flags="${ncbi_rp_R_flags}${ncbi_rp_R_sep}$x"
+       ncbi_rp_R_sep=:
+    done
+    NGS_LIBPATH="${ncbi_rp_L_flags}${ncbi_rp_R_flags}"
+ fi
+       fi
+       NGS_LIBS="$NGS_LIBPATH -lncbi-ngs-c++ -lngs-bam-c++ -lngs-adapt-c++ -lngs-c++"
+    else
+       NGS_INCLUDE=""
+       NGS_LIBS="-lncbi-ngs-c++ -lngs-bam-c++ -lngs-adapt-c++ -lngs-c++"
+       in_path=
+    fi
+    { echo "$as_me:$LINENO: checking for libncbi-ngs-c++$in_path" >&5
+echo $ECHO_N "checking for libncbi-ngs-c++$in_path... $ECHO_C" >&6; }
+if test "${ncbi_cv_lib_ngs+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  CPPFLAGS="$extra_inc $NGS_INCLUDE $orig_CPPFLAGS"
+       LIBS="$NGS_LIBS $VDB_LIBS $orig_LIBS"
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <ncbi-vdb/NGS.hpp>
+                          #include <ngs-bam/ngs-bam.hpp>
+int
+main ()
+{
+ncbi::NGS::setAppVersionString("conftest.0.0.0");
+             ngs::ReadCollection coll
+             = NGS_BAM::openReadCollection("foo.bam");
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_lib_ngs=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ncbi_cv_lib_ngs=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ncbi_cv_lib_ngs" >&5
+echo "${ECHO_T}$ncbi_cv_lib_ngs" >&6; }
+    if test "$ncbi_cv_lib_ngs" = "no"; then
+       if test "${with_ngs:=no}" != no; then
+       { { echo "$as_me:$LINENO: error: --with-ngs explicitly specified, but no usable version found." >&5
+echo "$as_me: error: --with-ngs explicitly specified, but no usable version found." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    fi
+ fi
+ if test "$with_ngs" = "no"; then
+    NGS_PATH="No_NGS"
+    NGS_INCLUDE=
+    NGS_LIBS=
+ else
+              WithPackages="$WithPackages${WithPackagesSep}NGS"; WithPackagesSep=" "
+    NGS_INCLUDE="$extra_inc $NGS_INCLUDE"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBNGS 1
+_ACEOF
+
+ fi
+
+
+
+   if test -n "$NGS_LIBS"; then
+      if test -f "$NGS_LIBDIR/libncbi-ngs-c++-static.a"; then
+         NGS_STATIC_LIBS="-L$NGS_LIBDIR -lncbi-ngs-c++-static"
+         NGS_STATIC_LIBS="$NGS_STATIC_LIBS -lngs-bam-c++-static"
+         NGS_STATIC_LIBS="$NGS_STATIC_LIBS -lngs-adapt-c++-static"
+         NGS_STATIC_LIBS="$NGS_STATIC_LIBS -lngs-c++-static"
+      else
+         NGS_STATIC_LIBS=$NGS_LIBS
+      fi
+   else
+      if test "${with_ngs:=no}" != no; then
+       { { echo "$as_me:$LINENO: error: --with-ngs explicitly specified, but no usable version found." >&5
+echo "$as_me: error: --with-ngs explicitly specified, but no usable version found." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
    fi
 fi
 
@@ -53703,7 +53981,7 @@ for x in ChaosMonkey Int8GI StrictGI PSGLoader GCC KCC ICC VisualAge CompaqCompi
           ;;
       esac
    done
-  for x in UUID FUSE Iconv LIBUNWIND LIBDW BACKWARD_CPP Z LocalZ BZ2 LocalBZ2 LZO PCRE LocalPCRE MBEDTLS GMP GCRYPT NETTLE GNUTLS OPENSSL KRB5 CURL Sybase DBLib FreeTDS MySQL BerkeleyDB BerkeleyDB++ ODBC PYTHON PYTHON25 PYTHON26 PYTHON27 PYTHON3 PERL Boost.Chrono Boost.Filesystem Boost.Iostreams Boost.Program-Options Boost.Regex Boost.Serialization Boost.Spirit Boost.System Boost.Test Boost.Test.Included Boost.Thread C-Toolkit OpenGL MESA GLUT GLEW wxWidgets wx2.8 Fast-CGI LocalSSS LocalMSGMAIL2 SSSUTILS LocalNCBILS NCBILS2 SSSDB SP ORBacus ICU EXPAT SABLOT LIBXML LIBXSLT LIBEXSLT Xerces Xalan Zorba SQLITE3 SQLITE3ASYNC VDB OECHEM SGE MUPARSER HDF5 JPEG PNG TIFF GIF UNGIF XPM GL2PS FreeType FTGL MAGIC MIMETIC GSOAP AVRO Cereal SASL2 MONGODB MONGODB3 LEVELDB GMOCK LAPACK LMDB LocalLMDB LIBUV LIBSSH2 CASSANDRA NGHTTP2 H2O INFLUXDB LIBXLSXWRITER PROTOBUF GRPC MSGSL AWS_SDK HIREDIS; do
+  for x in UUID FUSE Iconv LIBUNWIND LIBDW BACKWARD_CPP Z LocalZ BZ2 LocalBZ2 LZO PCRE LocalPCRE MBEDTLS GMP GCRYPT NETTLE GNUTLS OPENSSL KRB5 CURL Sybase DBLib FreeTDS MySQL BerkeleyDB BerkeleyDB++ ODBC PYTHON PYTHON25 PYTHON26 PYTHON27 PYTHON3 PERL Boost.Chrono Boost.Filesystem Boost.Iostreams Boost.Program-Options Boost.Regex Boost.Serialization Boost.Spirit Boost.System Boost.Test Boost.Test.Included Boost.Thread C-Toolkit OpenGL MESA GLUT GLEW wxWidgets wx2.8 Fast-CGI LocalSSS LocalMSGMAIL2 SSSUTILS LocalNCBILS NCBILS2 SSSDB SP ORBacus ICU EXPAT SABLOT LIBXML LIBXSLT LIBEXSLT Xerces Xalan Zorba SQLITE3 SQLITE3ASYNC VDB NGS OECHEM SGE MUPARSER HDF5 JPEG PNG TIFF GIF UNGIF XPM GL2PS FreeType FTGL MAGIC MIMETIC GSOAP AVRO Cereal SASL2 MONGODB MONGODB3 LEVELDB GMOCK LAPACK LMDB LocalLMDB LIBUV LIBSSH2 CASSANDRA NGHTTP2 H2O INFLUXDB LIBXLSXWRITER PROTOBUF GRPC MSGSL AWS_SDK HIREDIS; do
       case " $WithPackages " in
          *" $x "*) ;;
          *) WithoutPackages="$WithoutPackages$WithoutPackagesSep$x"
@@ -53799,6 +54077,7 @@ c_ncbi_runpath=`echo "$ncbi_runpath" | sed -e 's:\\$\\$:\\$:g'`
 
 
 #AC_SUBST(real_srcdir)
+
 
 
 
@@ -55025,9 +55304,9 @@ LIBEXSLT_INCLUDE!$LIBEXSLT_INCLUDE$ac_delim
 LIBEXSLT_LIBS!$LIBEXSLT_LIBS$ac_delim
 SQLITE3_INCLUDE!$SQLITE3_INCLUDE$ac_delim
 SQLITE3_LIBS!$SQLITE3_LIBS$ac_delim
+NGS_INCLUDE!$NGS_INCLUDE$ac_delim
+NGS_LIBS!$NGS_LIBS$ac_delim
 OECHEM_INCLUDE!$OECHEM_INCLUDE$ac_delim
-OECHEM_LIBS!$OECHEM_LIBS$ac_delim
-SGE_INCLUDE!$SGE_INCLUDE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -55069,6 +55348,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+OECHEM_LIBS!$OECHEM_LIBS$ac_delim
+SGE_INCLUDE!$SGE_INCLUDE$ac_delim
 SGE_LIBS!$SGE_LIBS$ac_delim
 MUPARSER_INCLUDE!$MUPARSER_INCLUDE$ac_delim
 MUPARSER_LIBS!$MUPARSER_LIBS$ac_delim
@@ -55164,8 +55445,6 @@ C_LIBS!$C_LIBS$ac_delim
 OBJCXX_LIBS!$OBJCXX_LIBS$ac_delim
 GCCPCH!$GCCPCH$ac_delim
 RUNPATH_ORIGIN!$RUNPATH_ORIGIN$ac_delim
-NO_STRICT_ALIASING!$NO_STRICT_ALIASING$ac_delim
-D_SFX!$D_SFX$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -55207,6 +55486,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+NO_STRICT_ALIASING!$NO_STRICT_ALIASING$ac_delim
+D_SFX!$D_SFX$ac_delim
 DEBUG_SFX!$DEBUG_SFX$ac_delim
 LIB_OR_DLL!$LIB_OR_DLL$ac_delim
 FORCE_STATIC_LIB!$FORCE_STATIC_LIB$ac_delim
@@ -55302,8 +55583,6 @@ MYSQL_INCLUDE!$MYSQL_INCLUDE$ac_delim
 MYSQL_LIBS!$MYSQL_LIBS$ac_delim
 BERKELEYDB_INCLUDE!$BERKELEYDB_INCLUDE$ac_delim
 BERKELEYDB_LIBS!$BERKELEYDB_LIBS$ac_delim
-BERKELEYDB_STATIC_LIBS!$BERKELEYDB_STATIC_LIBS$ac_delim
-BERKELEYDB_CXX_LIBS!$BERKELEYDB_CXX_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -55345,6 +55624,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+BERKELEYDB_STATIC_LIBS!$BERKELEYDB_STATIC_LIBS$ac_delim
+BERKELEYDB_CXX_LIBS!$BERKELEYDB_CXX_LIBS$ac_delim
 BERKELEYDB_CXX_STATIC_LIBS!$BERKELEYDB_CXX_STATIC_LIBS$ac_delim
 ODBC_INCLUDE!$ODBC_INCLUDE$ac_delim
 ODBC_LIBS!$ODBC_LIBS$ac_delim
@@ -55416,6 +55697,7 @@ ncbi_xloader_vdbgraph!$ncbi_xloader_vdbgraph$ac_delim
 ncbi_xloader_wgs!$ncbi_xloader_wgs$ac_delim
 VDB_REQ!$VDB_REQ$ac_delim
 VDB_POST_LINK!$VDB_POST_LINK$ac_delim
+NGS_STATIC_LIBS!$NGS_STATIC_LIBS$ac_delim
 SP_INCLUDE!$SP_INCLUDE$ac_delim
 SP_LIBS!$SP_LIBS$ac_delim
 ORBACUS_INCLUDE!$ORBACUS_INCLUDE$ac_delim
@@ -55439,9 +55721,6 @@ XALAN_LIBS!$XALAN_LIBS$ac_delim
 XALAN_STATIC_LIBS!$XALAN_STATIC_LIBS$ac_delim
 ZORBA_INCLUDE!$ZORBA_INCLUDE$ac_delim
 ZORBA_LIBS!$ZORBA_LIBS$ac_delim
-ZORBA_STATIC_LIBS!$ZORBA_STATIC_LIBS$ac_delim
-SQLITE3_STATIC_LIBS!$SQLITE3_STATIC_LIBS$ac_delim
-FREETYPE_INCLUDE!$FREETYPE_INCLUDE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -55483,6 +55762,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+ZORBA_STATIC_LIBS!$ZORBA_STATIC_LIBS$ac_delim
+SQLITE3_STATIC_LIBS!$SQLITE3_STATIC_LIBS$ac_delim
+FREETYPE_INCLUDE!$FREETYPE_INCLUDE$ac_delim
 FREETYPE_LIBS!$FREETYPE_LIBS$ac_delim
 GSOAP_PATH!$GSOAP_PATH$ac_delim
 AVRO_STATIC_LIBS!$AVRO_STATIC_LIBS$ac_delim
@@ -55551,7 +55833,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 66; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 69; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
