configure(.ac): Add FTGL as a gbench requirement; generally resync up-front checks (in explicit --with-gbench mode) with later checks (determining whether to enable the "gbench" feature for REQUIRES).
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@73948 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -4193,6 +4193,34 @@ echo "$as_me: error: incompatible options: --without-glew_mx but --with-gbench" 
       else
          with_glew_mx=yes
       fi
+     if test "$with_wxwidgets" = "no"; then
+         { { echo "$as_me:$LINENO: error: incompatible options: --without-wxwidgets but --with-gbench" >&5
+echo "$as_me: error: incompatible options: --without-wxwidgets but --with-gbench" >&2;}
+   { (exit 1); exit 1; }; }
+      else
+         with_wxwidgets=yes
+      fi
+     if test "$with_ftgl" = "no"; then
+         { { echo "$as_me:$LINENO: error: incompatible options: --without-ftgl but --with-gbench" >&5
+echo "$as_me: error: incompatible options: --without-ftgl but --with-gbench" >&2;}
+   { (exit 1); exit 1; }; }
+      else
+         with_ftgl=yes
+      fi
+     if test "$with_sqlite3" = "no"; then
+         { { echo "$as_me:$LINENO: error: incompatible options: --without-sqlite3 but --with-gbench" >&5
+echo "$as_me: error: incompatible options: --without-sqlite3 but --with-gbench" >&2;}
+   { (exit 1); exit 1; }; }
+      else
+         with_sqlite3=yes
+      fi
+     if test "$with_bdb" = "no"; then
+         { { echo "$as_me:$LINENO: error: incompatible options: --without-bdb but --with-gbench" >&5
+echo "$as_me: error: incompatible options: --without-bdb but --with-gbench" >&2;}
+   { (exit 1); exit 1; }; }
+      else
+         with_bdb=yes
+      fi
 
    : ${with_projects=scripts/projects/ncbi_gbench.lst}
 elif test "$with_jni" = "yes" ; then
@@ -46213,6 +46241,14 @@ if test "$with_gbench" != "no"  -a  -d "$real_srcdir/src/app/gbench"; then
    fi
    if test "$with_opengl" = "no"; then
      reason="$reason${sep}OpenGL"
+     sep=", "
+   fi
+   if test "$with_glew_mx" = "no"; then
+     reason="$reason${sep}GLEWmx"
+     sep=", "
+   fi
+   if test "$with_ftgl" = "no"; then
+     reason="$reason${sep}FTGL"
      sep=", "
    fi
    if test "$with_sqlite3" = "no"; then
