configure(.ac): accommodate ICC version numbers with three or more components; fail immediately when not sure how to distill a version number rather than leaving it unchanged and yielding preprocessor errors.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@55659 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -4816,10 +4816,15 @@ case "$compiler:$ncbi_compiler_ver" in
     WorkShop*:?.?? )   ncbi_compiler_sed='s/\([0-9]\)\.\([0-9][0-9]\)/\1\20/' ;;
     WorkShop*:[6-9].?) ncbi_compiler_sed='s/\([0-9]\)\.\([0-9\)/\10\20/' ;;
     ICC:??.? )  ncbi_compiler_sed='s/\([0-9][0-9]\)\.\([0-9]\)/\1\20/' ;;
+    ICC:??.?.? | \
+    ICC:??.?.?.* ) ncbi_compiler_sed='s/\([0-9][0-9]\)\.\([0-9]\)\.\([0-9]\).*/\1\2\3/' ;;
     *:?.?.?)    ncbi_compiler_sed='s/\([0-9]\)\.\([0-9]\)\.\([0-9]\)/\1\2\3/' ;;
     *:?.??*)    ncbi_compiler_sed='s/\([0-9]\)\.\([0-9][0-9]\).*/\1\2/' ;;
     *:?.?)      ncbi_compiler_sed='s/\([0-9]\).\([0-9]\)/\1\20/' ;;
     *:?)        ncbi_compiler_sed='s/\([0-9]\)/\100/' ;;
+    *)    { { echo "$as_me:$LINENO: error: Do not know how to parse $compiler version number $ncbi_compiler_ver" >&5
+echo "$as_me: error: Do not know how to parse $compiler version number $ncbi_compiler_ver" >&2;}
+   { (exit 1); exit 1; }; } ;;
 esac
 ncbi_compiler_ver=`echo $ncbi_compiler_ver | sed "$ncbi_compiler_sed"`
 compiler_version=$ncbi_compiler_ver
