configure(.ac): Support --with-max-debug=thread (GCC-only).  JIRA: CXX-10523.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@85807 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -1666,8 +1666,8 @@ esac
 
 #### Check the passed arguments against the list of available ones
 x_with_list="\
-debug max-debug symbols optimization sse42 profiling code-coverage \
-tcheck dll static static-exe \
+debug max-debug max-debug=thread symbols optimization sse42 \
+profiling code-coverage tcheck dll static static-exe \
 plugin-auto-load bundles bin-release mt 64 exe runpath hard-runpath \
 lfs limited-linker skew-guard openmp \
 autodep suffix hostspec version execopy bincopy lib-rebuilds lib-rebuilds=ask \
@@ -1894,7 +1894,7 @@ Optional Packages:
 ===============================================================================
 =============== NCBI C++ Toolkit specific configuration flags =================
  --without-debug         build non-debug versions of libs and apps
- --with-max-debug        enable extra runtime checks (esp. of STL usage)
+ --with-max-debug(=TYPE) enable extra runtime checks (esp. of STL usage)
  --with-symbols          retain debugging symbols in non-debug mode
  --without-optimization  turn off optimization flags in non-debug mode
  --without-sse42         don't enable SSE 4.2 when optimizing
@@ -4665,7 +4665,7 @@ fi
 if test "$with_debug" = no; then
     : ${with_symbols=no}
     : ${with_optimization=yes}
-    if test "$with_max_debug" = yes; then
+    if test "${with_max_debug-no}" != no; then
        { { echo "$as_me:$LINENO: error: incompatible options: --without-debug but --with-max-debug" >&5
 echo "$as_me: error: incompatible options: --without-debug but --with-max-debug" >&2;}
    { (exit 1); exit 1; }; }
@@ -13806,13 +13806,23 @@ if test "$compiler" != "MSVC" ; then
       CPPFLAGS="-D_DEBUG $CPPFLAGS"
    fi
 
-   if test "$with_max_debug" = "yes"; then
+   if test "${with_max_debug-no}" != "no"; then
+      case "$compiler:$with_max_debug" in
+         GCC:thread ) sanitize=-fsanitize=thread ;;
+         GCC:yes    ) sanitize=-fsanitize=address ;;
+         *:yes      ) ;;
+         *          )
+            { { echo "$as_me:$LINENO: error: --with-max-debug=$with_max_debug unimplemented for compiler $compiler" >&5
+echo "$as_me: error: --with-max-debug=$with_max_debug unimplemented for compiler $compiler" >&2;}
+   { (exit 1); exit 1; }; }
+            ;;
+      esac
       case "$compiler" in
          GCC )
             CPPFLAGS="-D_GLIBCXX_DEBUG $CPPFLAGS"
-            CFLAGS="-fstack-check -fsanitize=address $CFLAGS"
-            CXXFLAGS="-fstack-check -fsanitize=address $CXXFLAGS"
-            LDFLAGS="-fsanitize=address $LDFLAGS"
+            CFLAGS="-fstack-check $sanitize $CFLAGS"
+            CXXFLAGS="-fstack-check $sanitize $CXXFLAGS"
+            LDFLAGS="$sanitize $LDFLAGS"
             ;;
          ICC )
             CPPFLAGS="-D_GLIBCXX_DEBUG $CPPFLAGS"
