configure(.ac): - Report an error if asked to use a non-existent or unreadable project list. - Name the project list when noting the possibility of running make all_p. - Generally clean up logic around with_projects.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@56695 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -3125,7 +3125,8 @@ echo "$as_me: error: --without-extra-action is not allowed" >&2;}
 fi
 
 case "$with_projects" in
- "") if test -r projects; then
+ ""|yes)
+     if test -r projects; then
         { echo "$as_me:$LINENO: using default projects file \"projects\"." >&5
 echo "$as_me: using default projects file \"projects\"." >&6;}
         with_projects=projects
@@ -3150,6 +3151,13 @@ echo "$as_me: WARNING: default projects file \"projects\" is a dangling link." >
  * ) PROJECTS="\$(top_srcdir)/$with_projects"
  ;;
 esac
+
+if test -n "$with_projects" -a \! -r "$with_projects"; then
+   test "$with_projects" = yes  &&  with_projects=projects
+   { { echo "$as_me:$LINENO: error: unable to read requested projects file \"$with_projects\"." >&5
+echo "$as_me: error: unable to read requested projects file \"$with_projects\"." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 # Check for custom optimization flags before potentially going with defaults.
 skip_fast_flags=no
@@ -33825,7 +33833,7 @@ else
      sep=", "
    fi
    if test -n "$reason" -a "$with_internal" = "yes"; then
-      if test -z "$with_projects"  -o  "$with_projects" = "no"; then
+      if test -z "$with_projects"; then
          { { echo "$as_me:$LINENO: error: --with-internal:  Cannot build INTERNAL projects: missing $reason" >&5
 echo "$as_me: error: --with-internal:  Cannot build INTERNAL projects: missing $reason" >&2;}
    { (exit 1); exit 1; }; }
@@ -36062,11 +36070,9 @@ if test "$with_flat_makefile" != "no"; then
    else
       cfm_flags='-remoteptb'
    fi
-   case "$with_projects" in
-      yes     ) cfm_flags="$cfm_flags -p projects" ;;
-      no | '' ) ;;
-      *       ) cfm_flags="$cfm_flags -p $with_projects" ;;
-   esac
+   if test -n "$with_projects"; then
+      cfm_flags="$cfm_flags -p $with_projects"
+   fi
    if test "$with_configure_dialog" = yes; then
       cfm_flags="$cfm_flags -cfg"
    fi
@@ -36110,7 +36116,8 @@ lib)
 esac
 
 if test -n "$with_projects"; then
-    build_proj="To build selected projects:  cd $builddir && make all_p"
+    build_proj="To build selected projects (as listed in \"$with_projects\"):
+  cd $builddir && make all_p"
 fi
 
 cat << EOCONF
