configure(.ac): When building with Clang, try to use LLVM libc++ even if the compiler defaults to GNU libstdc++, which is less certain to be C++11 compliant.  JIRA: CXX-3820, CXX-5157.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@63970 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -6907,6 +6907,80 @@ echo "${ECHO_T}$ncbi_cv_prog_cc_new_dtags" >&6; }
       ;;
 esac
 
+if $CXX -v 2>&1 | grep -q clang; then
+   { echo "$as_me:$LINENO: checking whether $CXX supports -stdlib=libc++" >&5
+echo $ECHO_N "checking whether $CXX supports -stdlib=libc++... $ECHO_C" >&6; }
+if test "${ncbi_cv_prog_cxx_stdlib_libcxx+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  orig_CXX=$CXX
+       CXX="$orig_CXX -stdlib=libc++"
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_prog_cxx_stdlib_libcxx=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ncbi_cv_prog_cxx_stdlib_libcxx=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+       CXX=$orig_CXX
+fi
+{ echo "$as_me:$LINENO: result: $ncbi_cv_prog_cxx_stdlib_libcxx" >&5
+echo "${ECHO_T}$ncbi_cv_prog_cxx_stdlib_libcxx" >&6; }
+   test "$ncbi_cv_prog_cxx_libcxx" = no  ||  CXX="$CXX -stdlib=libc++"
+fi
+
 { echo "$as_me:$LINENO: checking whether _LIBCPP_VERSION is declared" >&5
 echo $ECHO_N "checking whether _LIBCPP_VERSION is declared... $ECHO_C" >&6; }
 if test "${ac_cv_have_decl__LIBCPP_VERSION+set}" = set; then
