configure(.ac): fix new sanity check for project list existence to account for not necessarily running in $srcdir.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@56705 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -3152,10 +3152,15 @@ echo "$as_me: WARNING: default projects file \"projects\" is a dangling link." >
  ;;
 esac
 
-if test -n "$with_projects" -a \! -r "$with_projects"; then
-   test "$with_projects" = yes  &&  with_projects=projects
-   { { echo "$as_me:$LINENO: error: unable to read requested projects file \"$with_projects\"." >&5
-echo "$as_me: error: unable to read requested projects file \"$with_projects\"." >&2;}
+if test -n "$with_projects"; then
+   case "$with_projects" in
+      /* ) abs_projects=$projects              ;;
+      yes) abs_projects=$srcdir/projects       ;;
+      *  ) abs_projects=$srcdir/$with_projects ;;
+   esac
+   test -r "$abs_projects"  ||  \
+      { { echo "$as_me:$LINENO: error: unable to read requested projects file \"$abs_projects\"." >&5
+echo "$as_me: error: unable to read requested projects file \"$abs_projects\"." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
