Add a --with-relative-runpath=... flag to simplify specifying executable-relative runpaths, which can be cumbersome to quote and escape just right.  JIRA: CXX-2488.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@51060 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -888,7 +888,8 @@ Optional Packages:
  --with-universal        build universal binaries on Mac OS X
  --with-universal=CPUs   build universal binaries targeting the given CPUs
  --without-exe           do not build executables
- --with-runpath=         hard-code the runtime path to DLLs
+ --with-runpath=PATH     hard-code the runtime path to DLLs
+ --with-relative-runpath=P specify an executable-relative DLL search path
  --with-lfs              enable large file support to the extent possible
  --with-extra-action=    script to call after the configuration is complete
  --with-autodep          automatic generation of dependencies (GNU make)
@@ -1941,6 +1942,12 @@ if test "${with_runpath+set}" = set; then
 
 fi;
 
+# Check whether --with-relative-runpath or --without-relative-runpath was given.
+if test "${with_relative_runpath+set}" = set; then
+  withval="$with_relative_runpath"
+
+fi;
+
 # Check whether --with-lfs or --without-lfs was given.
 if test "${with_lfs+set}" = set; then
   withval="$with_lfs"
@@ -2848,7 +2855,7 @@ for x_arg in "$@" ; do
    case "$x_arg" in
       --with-extra-action= | --exec-prefix= | --with-projects= | --srcdir= \
       | --cache-file= | --build= | --host= | --target= | --with-runpath= \
-      | --x-includes= | --x-libraries= )
+      | --with-relative-runpath= | --x-includes= | --x-libraries= )
       { { echo "$as_me:$LINENO: error: $x_arg:  requires value;  use --help to show usage" >&5
 echo "$as_me: error: $x_arg:  requires value;  use --help to show usage" >&2;}
    { (exit 1); exit 1; }; }
@@ -2877,7 +2884,8 @@ echo "$as_me: error: $x_arg:  requires value;  use --help to show usage" >&2;}
       | --with-boost=* | --with-boost-tag=* | --with-orbacus=* | --with-sge=* \
       | --with-muparser=* | --with-hdf5=* | --with-jni=* | --with-magic=* \
       | --x-includes=* | --x-libraries=* | --with-3psw=* \
-      | --target=* | --with-runpath=* | --no-create | --no-recursion)
+      | --target=* | --with-runpath=* | --with-relative-runpath=* \
+      | --no-create | --no-recursion)
       ;;
 
       * )
@@ -5677,9 +5685,18 @@ if test -z "$CONF_f_runpath" ; then
    esac
 fi
 case "$host_os:$ncbi_cv_prog_cc_wl_rpath" in
-    linux*|solaris* ) RUNPATH_ORIGIN="$CONF_f_runpath'\$\$ORIGIN'" ;;
-    darwin*:yes     ) RUNPATH_ORIGIN="$CONF_f_runpath@executable_path" ;;
-    * )               RUNPATH_ORIGIN="-DNCBI_RPO_SUFFIX_EATER=" ;;
+    linux*|solaris* )
+        origin="'\$\$ORIGIN'"
+        RUNPATH_ORIGIN="$CONF_f_runpath$origin"
+        ;;
+    darwin*:yes )
+        origin='@executable_path'
+        RUNPATH_ORIGIN="$CONF_f_runpath$origin"
+        ;;
+    * )
+        origin=
+        RUNPATH_ORIGIN="-DNCBI_RPO_SUFFIX_EATER="
+        ;;
 esac
 
 case "$compiler:$compiler_version:$with_bin_release" in
@@ -7896,6 +7913,22 @@ fi
 
 
 #### Set runpath (may depend on build root)
+if test -n "$with_relative_runpath"; then
+   if test "$with_runpath" = "no"; then
+      { { echo "$as_me:$LINENO: error: incompatible options: --without-runpath and --with-relative-runpath=$with_relative_runpath" >&5
+echo "$as_me: error: incompatible options: --without-runpath and --with-relative-runpath=$with_relative_runpath" >&2;}
+   { (exit 1); exit 1; }; }
+   elif test -z "$origin"; then
+      { { echo "$as_me:$LINENO: error: Do not know how to specify relative runpaths on $host" >&5
+echo "$as_me: error: Do not know how to specify relative runpaths on $host" >&2;}
+   { (exit 1); exit 1; }; }
+   else
+      rp=`echo "$origin/$with_relative_runpath" | \
+          sed "s,:,:$origin/,g; s,/.:,:,g; s,/.\$,,"`
+      with_runpath="$rp${with_runpath+:$with_runpath}"
+   fi
+fi
+
 if test -z "$with_runpath"; then
    # Don't allow libdir values containing variable expansions,
    # including in particular the default "${exec_prefix}/lib"
