configure(.ac): Implement a --with-static-vdb flag that puts static libraries (if available) in VDB_LIBS, not just VDB_STATIC_LIBS.  Have --with-bin-release soft-imply this flag: explicit --with-static-vdb usage implies --with-vdb, which fails if VDB is unavailable altogether, but --with-bin-release won't impose a hard requirement on VDB, just favor static builds thereof.  JIRA: CXX-7756, SRA-4594.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@73348 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -1608,7 +1608,7 @@ autodep suffix hostspec version execopy bincopy lib-rebuilds lib-rebuilds=ask \
 deactivation makefile-auto-update projects flat-makefile configure-dialog \
 check ncbi-public strip pch caution ccache distcc \
 ncbi-c wxwidgets wxwidgets-ucs fastcgi sss sssdb sssutils included-sss \
-geo included-geo vdb downloaded-vdb \
+geo included-geo vdb downloaded-vdb static-vdb \
 z bz2 lzo pcre gmp gcrypt nettle gnutls openssl krb5 \
 sybase sybase-local sybase-new ftds mysql \
 orbacus freetype ftgl opengl mesa glut glew glew-mx \
@@ -1877,6 +1877,7 @@ Optional Packages:
  --with-vdb=DIR          use NCBI SRA/VDB Toolkit installation in DIR
  --without-vdb           do not use the NCBI SRA/VDB Toolkit
  --with-downloaded-vdb   download and build SRA/VDB from GitHub
+ --with-static-vdb       always link statically against SRA/VDB
  --with-z=DIR            use zlib installation in DIR
  --without-z             use internal copy of zlib
  --with-bz2=DIR          use bzlib installation in DIR
@@ -3297,6 +3298,12 @@ if test "${with_downloaded_vdb+set}" = set; then
 fi
 
 
+# Check whether --with-static-vdb was given.
+if test "${with_static_vdb+set}" = set; then
+  withval=$with_static_vdb;
+fi
+
+
 ## Third-party and system packages
 
 # Check whether --with-z was given.
@@ -4265,6 +4272,20 @@ echo "$as_me: error: incompatible options: --without-vdb but
       ;;
    yes: )
       with_vdb=yes
+      ;;
+esac
+
+case "$with_static_vdb:$with_vdb" in
+   yes:no )
+      { { echo "$as_me:$LINENO: error: incompatible options: --without-vdb but --with-static-vdb" >&5
+echo "$as_me: error: incompatible options: --without-vdb but --with-static-vdb" >&2;}
+   { (exit 1); exit 1; }; }
+      ;;
+   yes: )
+      with_vdb=yes
+      ;;
+   :* )
+      with_static_vdb=$with_bin_release
       ;;
 esac
 
@@ -41160,6 +41181,9 @@ echo "${ECHO_T}$ncbi_cv_lib_ncbi_vdb" >&6; }
                    WithPackages="$WithPackages${WithPackagesSep}VDB"; WithPackagesSep=" "
          if test -f "$VDB_LIBDIR/libncbi-vdb-static.a"; then
             VDB_STATIC_LIBS="-L$VDB_LIBDIR -lncbi-vdb-static $vdb_deps"
+            if test "$with_static_vdb" = yes; then
+               VDB_LIBS=$VDB_STATIC_LIBS
+            fi
          else
             VDB_STATIC_LIBS=$VDB_LIBS
          fi
