Rework most NCBI_*_EXPORT macros in terms of generic new NCBI_DLL_EXPORT and NCBI_DLL_IMPORT macros, which expand to __attribute__((visibility("default"))) in GCC 4.x for the sake of builds (most notably under Xcode in Release mode) that specify -fvisibility=hidden.  As such, move the bulk of the definitions to <common/ncbi_export.h>, turn <corelib/mswin_export.h> into a forwarding header, and update references thereto (or drop them altogether if they were redundant).
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@42576 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -17651,6 +17651,67 @@ _ACEOF
 
 fi
 
+echo "$as_me:$LINENO: checking whether $CC supports __attribute__((visibility(\"default\")))" >&5
+echo $ECHO_N "checking whether $CC supports __attribute__((visibility(\"default\")))... $ECHO_C" >&6
+if test "${ncbi_cv_c_attribute_visibility_default+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+__attribute__((visibility("default"))) void f(void); void f(void) {}
+int
+main ()
+{
+f();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_c_attribute_visibility_default=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ncbi_cv_c_attribute_visibility_default=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ncbi_cv_c_attribute_visibility_default" >&5
+echo "${ECHO_T}$ncbi_cv_c_attribute_visibility_default" >&6
+if test $ncbi_cv_c_attribute_visibility_default = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ATTRIBUTE_VISIBILITY_DEFAULT 1
+_ACEOF
+
+fi
+
 echo "$as_me:$LINENO: checking whether the C compiler supports C99 restrict" >&5
 echo $ECHO_N "checking whether the C compiler supports C99 restrict... $ECHO_C" >&6
 if test "${ncbi_cv_c_restrict+set}" = set; then
