- Don't automatically disable the whole gui tree just because FLTK is   missing; the requirement is shifting, and REQUIRES suffices. - Consider Berkeley DB 4.6.x to be supported.  (Don't warn about using it.) - Suppress some other potential warnings.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@35358 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -21271,7 +21271,7 @@ echo "${ECHO_T}$ncbi_cv_lib_berkeley_db_version" >&6
 echo "$as_me: WARNING: Your Berkeley DB version is too old to use.  (Needed >= 4.3.)" >&2;}
             with_bdb=no
             ;;
-         4.[3-5].* ) ;;
+         4.[3-6].* ) ;;
          * )
             { echo "$as_me:$LINENO: WARNING: Untested Berkeley DB version; may prove incompatible." >&5
 echo "$as_me: WARNING: Untested Berkeley DB version; may prove incompatible." >&2;}
@@ -22609,7 +22609,8 @@ if test "$with_boost" != "no"; then
    else
       BOOST_PATH=$with_boost
    fi
-   ncbi_fix_dir_tmp=`if cd $BOOST_PATH; then $as_unset PWD || test "${PWD+set}" != set || { PWD=; export PWD; }; /bin/pwd; fi`
+   if test -d "$BOOST_PATH"; then
+      ncbi_fix_dir_tmp=`if cd $BOOST_PATH; then $as_unset PWD || test "${PWD+set}" != set || { PWD=; export PWD; }; /bin/pwd; fi`
  case "$ncbi_fix_dir_tmp" in
     /.*) ncbi_fix_dir_tmp2=`cd $BOOST_PATH && $smart_pwd 2>/dev/null`
          if test -n "$ncbi_fix_dir_tmp2" -a -d "$ncbi_fix_dir_tmp2"; then
@@ -22623,6 +22624,7 @@ if test "$with_boost" != "no"; then
          ;;
     /*) BOOST_PATH=$ncbi_fix_dir_tmp ;;
  esac
+   fi
    : ${BOOST_INCLUDE=-I$BOOST_PATH/include}
    BOOST_LIBPATH_=$BOOST_PATH/lib
    if test -z "${BOOST_LIBPATH+set}"; then
@@ -25639,7 +25641,7 @@ if test "$with_wxwidgets" != "no" ; then
          fi
          ;;
       * )
-         baseflags=`$gtkconf --cflags`
+         baseflags=`$gtkconf --cflags 2>/dev/null`
          basesed=''
          libsed=''
          ;;
@@ -25779,7 +25781,7 @@ else
    WXWIDGETS_STATIC_LIBS=`$wxconf --libs --static | sed -e "$basesed"`
    WXWIDGETS_GL_LIBS=`$wxconf --gl-libs | sed -e "$basesed"`
    WXWIDGETS_GL_STATIC_LIBS=`$wxconf --gl-libs --static | sed -e "$basesed"`
-   WXWIDGETS_POST_LINK=`$wxconf --rezflags`
+   WXWIDGETS_POST_LINK=`$wxconf --rezflags 2>/dev/null`
    test -n "$WXWIDGETS_POST_LINK"  ||  WXWIDGETS_POST_LINK=:
 
 cat >>confdefs.h <<\_ACEOF
@@ -26358,7 +26360,8 @@ if test "${with_orbacus:-yes}" = yes; then
 elif test "$with_orbacus" != no; then
     ORBACUS_PATH=$with_orbacus
 fi
-ncbi_fix_dir_tmp=`if cd $ORBACUS_PATH; then $as_unset PWD || test "${PWD+set}" != set || { PWD=; export PWD; }; /bin/pwd; fi`
+if test -d "$ORBACUS_PATH"; then
+   ncbi_fix_dir_tmp=`if cd $ORBACUS_PATH; then $as_unset PWD || test "${PWD+set}" != set || { PWD=; export PWD; }; /bin/pwd; fi`
  case "$ncbi_fix_dir_tmp" in
     /.*) ncbi_fix_dir_tmp2=`cd $ORBACUS_PATH && $smart_pwd 2>/dev/null`
          if test -n "$ncbi_fix_dir_tmp2" -a -d "$ncbi_fix_dir_tmp2"; then
@@ -26372,6 +26375,7 @@ ncbi_fix_dir_tmp=`if cd $ORBACUS_PATH; then $as_unset PWD || test "${PWD+set}" !
          ;;
     /*) ORBACUS_PATH=$ncbi_fix_dir_tmp ;;
  esac
+fi
 if test "$with_orbacus" != no; then
    fullpath=${ORBACUS_PATH}/${DEBUG_SFX}${mt_sfx}${bit64_sfx}
    if test -f ${fullpath}/inc/OB/Config.h ; then
@@ -26833,7 +26837,8 @@ fi
 : ${SABLOT_PATH=$NCBI/Sablot}
 vpath="$SABLOT_PATH/${compiler_vpfx}build"
 test -d "$vpath"  &&  SABLOT_PATH=$vpath
-ncbi_fix_dir_tmp=`if cd $SABLOT_PATH; then $as_unset PWD || test "${PWD+set}" != set || { PWD=; export PWD; }; /bin/pwd; fi`
+if test -d "$SABLOT_PATH"; then
+   ncbi_fix_dir_tmp=`if cd $SABLOT_PATH; then $as_unset PWD || test "${PWD+set}" != set || { PWD=; export PWD; }; /bin/pwd; fi`
  case "$ncbi_fix_dir_tmp" in
     /.*) ncbi_fix_dir_tmp2=`cd $SABLOT_PATH && $smart_pwd 2>/dev/null`
          if test -n "$ncbi_fix_dir_tmp2" -a -d "$ncbi_fix_dir_tmp2"; then
@@ -26847,6 +26852,7 @@ ncbi_fix_dir_tmp=`if cd $SABLOT_PATH; then $as_unset PWD || test "${PWD+set}" !=
          ;;
     /*) SABLOT_PATH=$ncbi_fix_dir_tmp ;;
  esac
+fi
 if test "$with_sablot" != "no"; then
     case "$with_sablot" in
        yes | "" ) ;;
@@ -29458,19 +29464,12 @@ if test "$with_gui" = "no" ; then
    NoConfProjects="$NoConfProjects gui"
 fi
 
-if test ! -f ${real_srcdir}/src/gui/Makefile.in  -o  ! -d ${real_srcdir}/include/gui \
-    -o  "$with_fltk" = "no"
-then
+if test ! -f ${real_srcdir}/src/gui/Makefile.in \
+   -o  ! -d ${real_srcdir}/include/gui; then
    if test "$with_gui" = "yes" ; then
-      if test "$with_fltk" = "no" ; then
-         { { echo "$as_me:$LINENO: error: --with-gui:  FLTK package is missing" >&5
-echo "$as_me: error: --with-gui:  FLTK package is missing" >&2;}
-   { (exit 1); exit 1; }; }
-      else
-         { { echo "$as_me:$LINENO: error: --with-gui:  GUI sources are missing" >&5
+      { { echo "$as_me:$LINENO: error: --with-gui:  GUI sources are missing" >&5
 echo "$as_me: error: --with-gui:  GUI sources are missing" >&2;}
    { (exit 1); exit 1; }; }
-      fi
    fi
    with_gui="no"
 fi
