configure(.ac), config.h.in: Explicitly check for SIMD vector math support, which doesn't strictly correlate with having <x86intrin.h> (at least when building with ICC, which piggybacks on GCC's headers and libraries); clean up a stray tab that slipped in when tightening the check for SSE 4.1 support. JIRA: SRA-2329.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@63921 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -22742,6 +22742,80 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 orig_CFLAGS=$CFLAGS
 
+{ echo "$as_me:$LINENO: checking whether $CC supports SIMD vector arithmetic" >&5
+echo $ECHO_N "checking whether $CC supports SIMD vector arithmetic... $ECHO_C" >&6; }
+if test "${ncbi_cv_cc_vector_math+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+typedef int TVector __attribute__((vector_size(16)));
+int
+main ()
+{
+TVector v1, v2;  v1 ^= v2;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_cc_vector_math=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ncbi_cv_cc_vector_math=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ncbi_cv_cc_vector_math" >&5
+echo "${ECHO_T}$ncbi_cv_cc_vector_math" >&6; }
+if test "$ncbi_cv_cc_vector_math" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_VECTOR_MATH 1
+_ACEOF
+
+fi
+
 { echo "$as_me:$LINENO: checking whether $CC supports -funsafe-math-optimizations" >&5
 echo $ECHO_N "checking whether $CC supports -funsafe-math-optimizations... $ECHO_C" >&6; }
 if test "${ncbi_cv_cc_unsafe_math+set}" = set; then
@@ -22827,7 +22901,7 @@ int
 main ()
 {
 double v __attribute__((__vector_size__(16)));
-	   __builtin_ia32_shufpd(v, v, 1);
+           __builtin_ia32_shufpd(v, v, 1);
   ;
   return 0;
 }
