configure(.ac): Strictly require libstdc++.a in GCC --with-bin-release builds.
Historically, such configurations would fall back (with configure-time
warnings) to libstdc++.so if necessary.  JIRA: RW-690.

git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@84137 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -9969,8 +9969,9 @@ case "$compiler:$compiler_version:$with_bin_release" in
           LINK=$C_LINK
           ;;
        *)
-          { echo "$as_me:$LINENO: WARNING: Unable to find static libstdc++ requested by --with-bin-release." >&5
-echo "$as_me: WARNING: Unable to find static libstdc++ requested by --with-bin-release." >&2;}
+          { { echo "$as_me:$LINENO: error: Unable to find static libstdc++ requested by --with-bin-release." >&5
+echo "$as_me: error: Unable to find static libstdc++ requested by --with-bin-release." >&2;}
+   { (exit 1); exit 1; }; }
           ;;
     esac
     ;;
