Support using (and potentially finding) protobuf separately from gRPC.
When generating sources (in Makefile.protobuf.in), re-run protoc with
grpc_cpp_plugin only when the latter is available.  JIRA: CXX-10160.

git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@83079 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -863,6 +863,8 @@ H2O_INCLUDE
 H2O_LIBS
 LIBXLSXWRITER_INCLUDE
 LIBXLSXWRITER_LIBS
+PROTOBUF_INCLUDE
+PROTOBUF_LIBS
 GRPC_INCLUDE
 GRPC_LIBS
 AWS_SDK_INCLUDE
@@ -1101,6 +1103,7 @@ CASSANDRA_STATIC_LIBS
 NGHTTP2_STATIC_LIBS
 H2O_STATIC_LIBS
 LIBXLSXWRITER_STATIC_LIBS
+PROTOBUF_BIN
 GRPC_UNSECURE_LIBS
 GRPC_REFLECTION_LIBS
 GRPC_BIN
@@ -1679,8 +1682,8 @@ sp expat sablot libxml libxslt libexslt xerces xalan zorba \
 oechem sge muparser hdf5 \
 gif jpeg tiff png xpm \
 magic curl mimetic gsoap avro cereal sasl2 mongodb mongodb3 gmock lapack lmdb \
-libuv libssh2 cassandra nghttp2 h2o libxlsxwriter grpc msgsl aws-sdk 3psw \
-local-lbsm ncbi-crypt connext \
+libuv libssh2 cassandra nghttp2 h2o libxlsxwriter protobuf grpc msgsl aws-sdk \
+3psw local-lbsm ncbi-crypt connext \
 serial objects dbapi app ctools gui algo internal gbench"
 
 x_with_list=`echo "$x_with_list" | sed 's/\([^ ][^ ]*\)/--with-\1 --without-\1/g'`
@@ -1754,8 +1757,8 @@ for x_arg in "$@" ; do
       | --with-mongodb=* | --with-mongodb3=* \
       | --with-gmock=* | --with-lapack=* | --with-lmdb=* | --with-libuv=* \
       | --with-libssh2=* | --with-cassandra=* | --with-nghttp2=* \
-      | --with-h2o=* | --with-libxlsxwriter=* | --with-grpc=* \
-      | --with-msgsl=* | --with-aws-sdk=* )
+      | --with-h2o=* | --with-libxlsxwriter=* \
+      | --with-protobuf=* | --with-grpc=* | --with-msgsl=* | --with-aws-sdk=* )
       # Confirm that the specified directory exists and is readable.
       dir=`echo $x_arg | sed -e 's/^[^=]*=//'`
       case "$x_arg" in
@@ -2095,7 +2098,9 @@ Optional Packages:
  --without-h2o           do not use h2o
  --with-libxlsxwriter=DIR use libxlsxwriter installation in DIR
  --without-libxlsxwriter do not use libxlsxwriter
- --with-grpc=DIR         use GRPC installation in DIR
+ --with-protobuf=DIR     use protocol buffers installation in DIR
+ --without-protobuf      do not use protocol buffers
+ --with-grpc=DIR         use GRPC (and protobuf) installation in DIR
  --without-grpc          do not use GRPC
  --with-msgsl=DIR        use Guideline Support Library installation in DIR
  --without-msgsl         do not use the Guideline Support Library
@@ -2697,6 +2702,12 @@ case "$with_3psw" in
    { (exit 1); exit 1; }; }
          else
             with_libxlsxwriter=no
+         fi
+        if test "${with_protobuf-no}" != "no"; then
+            { echo "$as_me: error: incompatible options: --with-protobuf but --without-3psw" >&2
+   { (exit 1); exit 1; }; }
+         else
+            with_protobuf=no
          fi
         if test "${with_grpc-no}" != "no"; then
             { echo "$as_me: error: incompatible options: --with-grpc but --without-3psw" >&2
@@ -4354,6 +4365,18 @@ fi
 # Check whether --with-libxlsxwriter was given.
 if test "${with_libxlsxwriter+set}" = set; then
   withval=$with_libxlsxwriter;
+fi
+
+
+# Check whether --with-protobuf was given.
+if test "${with_protobuf+set}" = set; then
+  withval=$with_protobuf;
+fi
+
+
+# Check whether --with-protobuf was given.
+if test "${with_protobuf+set}" = set; then
+  withval=$with_protobuf;
 fi
 
 
@@ -51082,6 +51105,193 @@ if test -d "$GRPC_PATH"; then
       fi
    done
 fi
+
+: ${PROTOBUF_PATH=$GRPC_PATH}
+
+if test "$with_protobuf" != "no"; then
+    case "$with_protobuf" in
+       yes | "" ) ;;
+       *        ) PROTOBUF_PATH=$with_protobuf ;;
+    esac
+    if test "$PROTOBUF_PATH" != /usr -a -d "$PROTOBUF_PATH"; then
+       in_path=" in $PROTOBUF_PATH"
+       if test -z "$PROTOBUF_INCLUDE" -a -d "$PROTOBUF_PATH/include"; then
+          PROTOBUF_INCLUDE="-I$PROTOBUF_PATH/include"
+       fi
+       if test -n "$PROTOBUF_LIBPATH"; then
+          :
+       elif test -d "$PROTOBUF_PATH/lib${bit64_sfx}"; then
+          ncbi_rp_L_flags=
+ ncbi_rp_L_sep=$CONF_f_libpath
+ if test "x${CONF_f_runpath}" = "x${CONF_f_libpath}"; then
+    for x in $PROTOBUF_PATH/lib${bit64_sfx}; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+    done
+    PROTOBUF_LIBPATH="${ncbi_rp_L_flags}"
+ else
+    ncbi_rp_R_flags=
+    ncbi_rp_R_sep=" $CONF_f_runpath"
+    for x in $PROTOBUF_PATH/lib${bit64_sfx}; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+       x=`echo $x | sed -e "$ncbi_rpath_sed"`
+       ncbi_rp_R_flags="${ncbi_rp_R_flags}${ncbi_rp_R_sep}$x"
+       ncbi_rp_R_sep=:
+    done
+    PROTOBUF_LIBPATH="${ncbi_rp_L_flags}${ncbi_rp_R_flags}"
+ fi
+       elif test -d "$PROTOBUF_PATH/lib"; then
+          ncbi_rp_L_flags=
+ ncbi_rp_L_sep=$CONF_f_libpath
+ if test "x${CONF_f_runpath}" = "x${CONF_f_libpath}"; then
+    for x in $PROTOBUF_PATH/lib; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+    done
+    PROTOBUF_LIBPATH="${ncbi_rp_L_flags}"
+ else
+    ncbi_rp_R_flags=
+    ncbi_rp_R_sep=" $CONF_f_runpath"
+    for x in $PROTOBUF_PATH/lib; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+       x=`echo $x | sed -e "$ncbi_rpath_sed"`
+       ncbi_rp_R_flags="${ncbi_rp_R_flags}${ncbi_rp_R_sep}$x"
+       ncbi_rp_R_sep=:
+    done
+    PROTOBUF_LIBPATH="${ncbi_rp_L_flags}${ncbi_rp_R_flags}"
+ fi
+       fi
+       PROTOBUF_LIBS="$PROTOBUF_LIBPATH -lprotobuf$D_SFX "
+    else
+       PROTOBUF_INCLUDE=""
+       PROTOBUF_LIBS="-lprotobuf$D_SFX "
+       in_path=
+    fi
+    { echo "$as_me:$LINENO: checking for libprotobuf$D_SFX$in_path" >&5
+echo $ECHO_N "checking for libprotobuf$D_SFX$in_path... $ECHO_C" >&6; }
+if test "${ncbi_cv_lib_protobuf+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  CPPFLAGS=" $PROTOBUF_INCLUDE $orig_CPPFLAGS"
+       LIBS="$PROTOBUF_LIBS $Z_LIBS $orig_LIBS"
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <google/protobuf/type.pb.h>
+int
+main ()
+{
+google::protobuf::Type t;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_lib_protobuf=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ncbi_cv_lib_protobuf=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ncbi_cv_lib_protobuf" >&5
+echo "${ECHO_T}$ncbi_cv_lib_protobuf" >&6; }
+    if test "$ncbi_cv_lib_protobuf" = "no"; then
+       if test "${with_protobuf:=no}" != no; then
+       { { echo "$as_me:$LINENO: error: --with-protobuf explicitly specified, but no usable version found." >&5
+echo "$as_me: error: --with-protobuf explicitly specified, but no usable version found." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    fi
+ fi
+ if test "$with_protobuf" = "no"; then
+    PROTOBUF_PATH="No_PROTOBUF"
+    PROTOBUF_INCLUDE=
+    PROTOBUF_LIBS=
+ else
+              WithPackages="$WithPackages${WithPackagesSep}PROTOBUF"; WithPackagesSep=" "
+    PROTOBUF_INCLUDE=" $PROTOBUF_INCLUDE"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBPROTOBUF 1
+_ACEOF
+
+ fi
+
+
+
+if test -n "$PROTOBUF_LIBS"; then
+   PROTOBUF_BIN=$PROTOBUF_PATH/bin
+else
+   if test "${with_grpc:=no}" != no; then
+       { { echo "$as_me:$LINENO: error: --with-grpc explicitly specified, but no usable version found." >&5
+echo "$as_me: error: --with-grpc explicitly specified, but no usable version found." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+fi
+
 if test "$with_grpc" != "no"; then
     case "$with_grpc" in
        yes | "" ) ;;
@@ -51157,10 +51367,10 @@ if test "$with_grpc" != "no"; then
     GRPC_LIBPATH="${ncbi_rp_L_flags}${ncbi_rp_R_flags}"
  fi
        fi
-       GRPC_LIBS="$GRPC_LIBPATH -lgrpc++ -lgrpc -lgpr -lprotobuf$D_SFX -lcares"
+       GRPC_LIBS="$GRPC_LIBPATH -lgrpc++ -lgrpc -lgpr $PROTOBUF_LIBS -lcares"
     else
        GRPC_INCLUDE=""
-       GRPC_LIBS="-lgrpc++ -lgrpc -lgpr -lprotobuf$D_SFX -lcares"
+       GRPC_LIBS="-lgrpc++ -lgrpc -lgpr $PROTOBUF_LIBS -lcares"
        in_path=
     fi
     { echo "$as_me:$LINENO: checking for libgrpc++$in_path" >&5
@@ -51168,7 +51378,7 @@ echo $ECHO_N "checking for libgrpc++$in_path... $ECHO_C" >&6; }
 if test "${ncbi_cv_lib_grpc+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  CPPFLAGS=" $GRPC_INCLUDE $orig_CPPFLAGS"
+  CPPFLAGS="$PROTOBUF_INCLUDE $GRPC_INCLUDE $orig_CPPFLAGS"
        LIBS="$GRPC_LIBS $OPENSSL_LIBS $Z_LIBS $orig_LIBS"
        cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -51246,7 +51456,7 @@ echo "$as_me: error: --with-grpc explicitly specified, but no usable version fou
     GRPC_LIBS=
  else
               WithPackages="$WithPackages${WithPackagesSep}GRPC"; WithPackagesSep=" "
-    GRPC_INCLUDE=" $GRPC_INCLUDE"
+    GRPC_INCLUDE="$PROTOBUF_INCLUDE $GRPC_INCLUDE"
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_LIBGRPC 1
@@ -52027,7 +52237,7 @@ for x in ChaosMonkey Int8GI StrictGI GCC KCC ICC VisualAge CompaqCompiler Cray W
           ;;
       esac
    done
-  for x in UUID FUSE Iconv LIBUNWIND LIBDW BACKWARD_CPP Z LocalZ BZ2 LocalBZ2 LZO PCRE LocalPCRE MBEDTLS GMP GCRYPT NETTLE GNUTLS OPENSSL KRB5 CURL Sybase DBLib FreeTDS MySQL BerkeleyDB BerkeleyDB++ ODBC PYTHON PYTHON25 PYTHON26 PYTHON27 PYTHON3 PERL Boost.Chrono Boost.Filesystem Boost.Iostreams Boost.Program-Options Boost.Regex Boost.Spirit Boost.System Boost.Test Boost.Test.Included Boost.Thread C-Toolkit OpenGL MESA GLUT GLEW wxWidgets wx2.8 Fast-CGI LocalSSS LocalMSGMAIL2 SSSUTILS LocalNCBILS NCBILS2 SSSDB SP ORBacus ICU EXPAT SABLOT LIBXML LIBXSLT LIBEXSLT Xerces Xalan Zorba SQLITE3 SQLITE3ASYNC VDB OECHEM SGE MUPARSER HDF5 JPEG PNG TIFF GIF UNGIF XPM FreeType FTGL MAGIC MIMETIC GSOAP AVRO Cereal SASL2 MONGODB MONGODB3 GMOCK LAPACK LMDB LocalLMDB LIBUV LIBSSH2 CASSANDRA NGHTTP2 H2O LIBXLSXWRITER GRPC MSGSL AWS_SDK; do
+  for x in UUID FUSE Iconv LIBUNWIND LIBDW BACKWARD_CPP Z LocalZ BZ2 LocalBZ2 LZO PCRE LocalPCRE MBEDTLS GMP GCRYPT NETTLE GNUTLS OPENSSL KRB5 CURL Sybase DBLib FreeTDS MySQL BerkeleyDB BerkeleyDB++ ODBC PYTHON PYTHON25 PYTHON26 PYTHON27 PYTHON3 PERL Boost.Chrono Boost.Filesystem Boost.Iostreams Boost.Program-Options Boost.Regex Boost.Spirit Boost.System Boost.Test Boost.Test.Included Boost.Thread C-Toolkit OpenGL MESA GLUT GLEW wxWidgets wx2.8 Fast-CGI LocalSSS LocalMSGMAIL2 SSSUTILS LocalNCBILS NCBILS2 SSSDB SP ORBacus ICU EXPAT SABLOT LIBXML LIBXSLT LIBEXSLT Xerces Xalan Zorba SQLITE3 SQLITE3ASYNC VDB OECHEM SGE MUPARSER HDF5 JPEG PNG TIFF GIF UNGIF XPM FreeType FTGL MAGIC MIMETIC GSOAP AVRO Cereal SASL2 MONGODB MONGODB3 GMOCK LAPACK LMDB LocalLMDB LIBUV LIBSSH2 CASSANDRA NGHTTP2 H2O LIBXLSXWRITER PROTOBUF GRPC MSGSL AWS_SDK; do
       case " $WithPackages " in
          *" $x "*) ;;
          *) WithoutPackages="$WithoutPackages$WithoutPackagesSep$x"
@@ -52120,6 +52330,7 @@ c_ncbi_runpath=`echo "$ncbi_runpath" | sed -e 's:\\$\\$:\\$:g'`
 
 
 #AC_SUBST(real_srcdir)
+
 
 
 
@@ -53440,6 +53651,8 @@ H2O_INCLUDE!$H2O_INCLUDE$ac_delim
 H2O_LIBS!$H2O_LIBS$ac_delim
 LIBXLSXWRITER_INCLUDE!$LIBXLSXWRITER_INCLUDE$ac_delim
 LIBXLSXWRITER_LIBS!$LIBXLSXWRITER_LIBS$ac_delim
+PROTOBUF_INCLUDE!$PROTOBUF_INCLUDE$ac_delim
+PROTOBUF_LIBS!$PROTOBUF_LIBS$ac_delim
 GRPC_INCLUDE!$GRPC_INCLUDE$ac_delim
 GRPC_LIBS!$GRPC_LIBS$ac_delim
 AWS_SDK_INCLUDE!$AWS_SDK_INCLUDE$ac_delim
@@ -53474,8 +53687,6 @@ NO_STRICT_ALIASING!$NO_STRICT_ALIASING$ac_delim
 D_SFX!$D_SFX$ac_delim
 DEBUG_SFX!$DEBUG_SFX$ac_delim
 LIB_OR_DLL!$LIB_OR_DLL$ac_delim
-FORCE_STATIC_LIB!$FORCE_STATIC_LIB$ac_delim
-APP_LIB_SETTING!$APP_LIB_SETTING$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -53517,6 +53728,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+FORCE_STATIC_LIB!$FORCE_STATIC_LIB$ac_delim
+APP_LIB_SETTING!$APP_LIB_SETTING$ac_delim
 APP_LIBS_SETTING!$APP_LIBS_SETTING$ac_delim
 LINK_DLL!$LINK_DLL$ac_delim
 has_dll_loadable!$has_dll_loadable$ac_delim
@@ -53612,8 +53825,6 @@ BERKELEYDB_LIBS!$BERKELEYDB_LIBS$ac_delim
 BERKELEYDB_STATIC_LIBS!$BERKELEYDB_STATIC_LIBS$ac_delim
 BERKELEYDB_CXX_LIBS!$BERKELEYDB_CXX_LIBS$ac_delim
 BERKELEYDB_CXX_STATIC_LIBS!$BERKELEYDB_CXX_STATIC_LIBS$ac_delim
-ODBC_INCLUDE!$ODBC_INCLUDE$ac_delim
-ODBC_LIBS!$ODBC_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -53655,6 +53866,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+ODBC_INCLUDE!$ODBC_INCLUDE$ac_delim
+ODBC_LIBS!$ODBC_LIBS$ac_delim
 BOOST_INCLUDE!$BOOST_INCLUDE$ac_delim
 BOOST_LIBPATH!$BOOST_LIBPATH$ac_delim
 BOOST_TAG!$BOOST_TAG$ac_delim
@@ -53750,8 +53963,6 @@ FREETYPE_LIBS!$FREETYPE_LIBS$ac_delim
 GSOAP_PATH!$GSOAP_PATH$ac_delim
 AVRO_STATIC_LIBS!$AVRO_STATIC_LIBS$ac_delim
 CEREAL_INCLUDE!$CEREAL_INCLUDE$ac_delim
-MONGODB_STATIC_LIBS!$MONGODB_STATIC_LIBS$ac_delim
-MONGODB3_STATIC_LIBS!$MONGODB3_STATIC_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -53793,6 +54004,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+MONGODB_STATIC_LIBS!$MONGODB_STATIC_LIBS$ac_delim
+MONGODB3_STATIC_LIBS!$MONGODB3_STATIC_LIBS$ac_delim
 LMDB_LIB!$LMDB_LIB$ac_delim
 LMDB_STATIC_LIBS!$LMDB_STATIC_LIBS$ac_delim
 LIBUV_STATIC_LIBS!$LIBUV_STATIC_LIBS$ac_delim
@@ -53801,6 +54014,7 @@ CASSANDRA_STATIC_LIBS!$CASSANDRA_STATIC_LIBS$ac_delim
 NGHTTP2_STATIC_LIBS!$NGHTTP2_STATIC_LIBS$ac_delim
 H2O_STATIC_LIBS!$H2O_STATIC_LIBS$ac_delim
 LIBXLSXWRITER_STATIC_LIBS!$LIBXLSXWRITER_STATIC_LIBS$ac_delim
+PROTOBUF_BIN!$PROTOBUF_BIN$ac_delim
 GRPC_UNSECURE_LIBS!$GRPC_UNSECURE_LIBS$ac_delim
 GRPC_REFLECTION_LIBS!$GRPC_REFLECTION_LIBS$ac_delim
 GRPC_BIN!$GRPC_BIN$ac_delim
@@ -53851,7 +54065,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 56; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 59; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
