Support using libunwind, but only by explicit request.  JIRA: GP-20582.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@78070 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -711,6 +711,8 @@ LDD
 CXXCPP
 TCHECK_CL
 AMQ
+LIBUNWIND_INCLUDE
+LIBUNWIND_LIBS
 Z_INCLUDE
 Z_LIBS
 BZ2_INCLUDE
@@ -1907,6 +1909,7 @@ Optional Packages:
  --without-vdb           do not use the NCBI SRA/VDB Toolkit
  --with-downloaded-vdb   download and build SRA/VDB from GitHub
  --with-static-vdb       always link statically against SRA/VDB
+ --with-libunwind(=DIR)  use libunwind (in DIR)
  --with-z=DIR            use zlib installation in DIR
  --without-z             use internal copy of zlib
  --with-bz2=DIR          use bzlib installation in DIR
@@ -2235,6 +2238,12 @@ case "$with_3psw" in
    { (exit 1); exit 1; }; }
          else
             with_vdb=no
+         fi
+        if test "${with_libunwind-no}" != "no"; then
+            { echo "$as_me: error: incompatible options: --with-libunwind but --without-3psw" >&2
+   { (exit 1); exit 1; }; }
+         else
+            with_libunwind=no
          fi
         if test "${with_z-no}" != "no"; then
             { echo "$as_me: error: incompatible options: --with-z but --without-3psw" >&2
@@ -3378,6 +3387,12 @@ fi
 
 
 ## Third-party and system packages
+
+# Check whether --with-libunwind was given.
+if test "${with_libunwind+set}" = set; then
+  withval=$with_libunwind;
+fi
+
 
 # Check whether --with-z was given.
 if test "${with_z+set}" = set; then
@@ -28066,6 +28081,185 @@ esac
 usr_lib='[/usr]*/lib/*[amdsprcv]*[23469]*'
 no_usr_lib="s,-L$usr_lib ,,g; s,-L/usr/lib/$multiarch ,,g"
 
+: ${with_libunwind:=no}
+if test "$with_libunwind" != "no"; then
+    case "$with_libunwind" in
+       yes | "" ) ;;
+       *        ) LIBUNWIND_PATH=$with_libunwind ;;
+    esac
+    if test "$LIBUNWIND_PATH" != /usr -a -d "$LIBUNWIND_PATH"; then
+       in_path=" in $LIBUNWIND_PATH"
+       if test -z "$LIBUNWIND_INCLUDE" -a -d "$LIBUNWIND_PATH/include"; then
+          LIBUNWIND_INCLUDE="-I$LIBUNWIND_PATH/include"
+       fi
+       if test -n "$LIBUNWIND_LIBPATH"; then
+          :
+       elif test -d "$LIBUNWIND_PATH/lib${bit64_sfx}"; then
+          ncbi_rp_L_flags=
+ ncbi_rp_L_sep=$CONF_f_libpath
+ if test "x${CONF_f_runpath}" = "x${CONF_f_libpath}"; then
+    for x in $LIBUNWIND_PATH/lib${bit64_sfx}; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+    done
+    LIBUNWIND_LIBPATH="${ncbi_rp_L_flags}"
+ else
+    ncbi_rp_R_flags=
+    ncbi_rp_R_sep=" $CONF_f_runpath"
+    for x in $LIBUNWIND_PATH/lib${bit64_sfx}; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+       x=`echo $x | sed -e "$ncbi_rpath_sed"`
+       ncbi_rp_R_flags="${ncbi_rp_R_flags}${ncbi_rp_R_sep}$x"
+       ncbi_rp_R_sep=:
+    done
+    LIBUNWIND_LIBPATH="${ncbi_rp_L_flags}${ncbi_rp_R_flags}"
+ fi
+       elif test -d "$LIBUNWIND_PATH/lib"; then
+          ncbi_rp_L_flags=
+ ncbi_rp_L_sep=$CONF_f_libpath
+ if test "x${CONF_f_runpath}" = "x${CONF_f_libpath}"; then
+    for x in $LIBUNWIND_PATH/lib; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+    done
+    LIBUNWIND_LIBPATH="${ncbi_rp_L_flags}"
+ else
+    ncbi_rp_R_flags=
+    ncbi_rp_R_sep=" $CONF_f_runpath"
+    for x in $LIBUNWIND_PATH/lib; do
+       case "$x" in
+          /lib | /usr/lib | /usr/lib32 | /usr/lib64 | /usr/lib/$multiarch )
+             continue
+             ;;
+       esac
+       ncbi_rp_L_flags="${ncbi_rp_L_flags}${ncbi_rp_L_sep}$x"
+       ncbi_rp_L_sep=" $CONF_f_libpath"
+       x=`echo $x | sed -e "$ncbi_rpath_sed"`
+       ncbi_rp_R_flags="${ncbi_rp_R_flags}${ncbi_rp_R_sep}$x"
+       ncbi_rp_R_sep=:
+    done
+    LIBUNWIND_LIBPATH="${ncbi_rp_L_flags}${ncbi_rp_R_flags}"
+ fi
+       fi
+       LIBUNWIND_LIBS="$LIBUNWIND_LIBPATH -lunwind "
+    else
+       LIBUNWIND_INCLUDE=""
+       LIBUNWIND_LIBS="-lunwind "
+       in_path=
+    fi
+    { echo "$as_me:$LINENO: checking for libunwind$in_path" >&5
+echo $ECHO_N "checking for libunwind$in_path... $ECHO_C" >&6; }
+if test "${ncbi_cv_lib_libunwind+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  CPPFLAGS=" $LIBUNWIND_INCLUDE $orig_CPPFLAGS"
+       LIBS="$LIBUNWIND_LIBS  $orig_LIBS"
+       cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <unwind.h>
+                    #include <stdlib.h>
+int
+main ()
+{
+_Unwind_Trace_Fn f; _Unwind_Backtrace(f, NULL);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ncbi_cv_lib_libunwind=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ncbi_cv_lib_libunwind=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ncbi_cv_lib_libunwind" >&5
+echo "${ECHO_T}$ncbi_cv_lib_libunwind" >&6; }
+    if test "$ncbi_cv_lib_libunwind" = "no"; then
+       if test "${with_libunwind:=no}" != no; then
+       { { echo "$as_me:$LINENO: error: --with-libunwind explicitly specified, but no usable version found." >&5
+echo "$as_me: error: --with-libunwind explicitly specified, but no usable version found." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    fi
+ fi
+ if test "$with_libunwind" = "no"; then
+    LIBUNWIND_PATH="No_LIBUNWIND"
+    LIBUNWIND_INCLUDE=
+    LIBUNWIND_LIBS=
+ else
+              WithPackages="$WithPackages${WithPackagesSep}LIBUNWIND"; WithPackagesSep=" "
+    LIBUNWIND_INCLUDE=" $LIBUNWIND_INCLUDE"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBUNWIND 1
+_ACEOF
+
+ fi
+
+
+
+LIBS="$LIBUNWIND_LIBS $LIBS"
+orig_LIBS="$LIBUNWIND_LIBS $orig_LIBS"
+
 if test "$with_z" != "no"; then
     case "$with_z" in
        yes | "" ) ;;
@@ -48186,7 +48380,7 @@ for x in ChaosMonkey Int8GI StrictGI GCC KCC ICC VisualAge CompaqCompiler Cray W
           ;;
       esac
    done
-  for x in UUID FUSE Iconv Z LocalZ BZ2 LocalBZ2 LZO PCRE LocalPCRE MBEDTLS GMP GCRYPT NETTLE GNUTLS OPENSSL KRB5 CURL Sybase DBLib FreeTDS MySQL BerkeleyDB BerkeleyDB++ ODBC PYTHON PYTHON25 PYTHON26 PYTHON27 PYTHON3 PERL Boost.Filesystem Boost.Iostreams Boost.Program-Options Boost.Regex Boost.Spirit Boost.System Boost.Test Boost.Test.Included Boost.Thread C-Toolkit OpenGL MESA GLUT GLEW wxWidgets wx2.8 Fast-CGI LocalSSS LocalMSGMAIL2 SSSUTILS LocalNCBILS NCBILS2 SSSDB SP ORBacus ICU EXPAT SABLOT LIBXML LIBXSLT LIBEXSLT Xerces Xalan Zorba SQLITE3 SQLITE3ASYNC VDB OECHEM SGE MUPARSER HDF5 JPEG PNG TIFF GIF UNGIF XPM FreeType FTGL MAGIC MIMETIC GSOAP AVRO Cereal SASL2 MONGODB GMOCK LAPACK LMDB LIBUV LIBSSH2 CASSANDRA LIBXLSXWRITER GRPC; do
+  for x in UUID FUSE Iconv LIBUNWIND Z LocalZ BZ2 LocalBZ2 LZO PCRE LocalPCRE MBEDTLS GMP GCRYPT NETTLE GNUTLS OPENSSL KRB5 CURL Sybase DBLib FreeTDS MySQL BerkeleyDB BerkeleyDB++ ODBC PYTHON PYTHON25 PYTHON26 PYTHON27 PYTHON3 PERL Boost.Filesystem Boost.Iostreams Boost.Program-Options Boost.Regex Boost.Spirit Boost.System Boost.Test Boost.Test.Included Boost.Thread C-Toolkit OpenGL MESA GLUT GLEW wxWidgets wx2.8 Fast-CGI LocalSSS LocalMSGMAIL2 SSSUTILS LocalNCBILS NCBILS2 SSSDB SP ORBacus ICU EXPAT SABLOT LIBXML LIBXSLT LIBEXSLT Xerces Xalan Zorba SQLITE3 SQLITE3ASYNC VDB OECHEM SGE MUPARSER HDF5 JPEG PNG TIFF GIF UNGIF XPM FreeType FTGL MAGIC MIMETIC GSOAP AVRO Cereal SASL2 MONGODB GMOCK LAPACK LMDB LIBUV LIBSSH2 CASSANDRA LIBXLSXWRITER GRPC; do
       case " $WithPackages " in
          *" $x "*) ;;
          *) WithoutPackages="$WithoutPackages$WithoutPackagesSep$x"
@@ -49409,6 +49603,8 @@ LDD!$LDD$ac_delim
 CXXCPP!$CXXCPP$ac_delim
 TCHECK_CL!$TCHECK_CL$ac_delim
 AMQ!$AMQ$ac_delim
+LIBUNWIND_INCLUDE!$LIBUNWIND_INCLUDE$ac_delim
+LIBUNWIND_LIBS!$LIBUNWIND_LIBS$ac_delim
 Z_INCLUDE!$Z_INCLUDE$ac_delim
 Z_LIBS!$Z_LIBS$ac_delim
 BZ2_INCLUDE!$BZ2_INCLUDE$ac_delim
@@ -49498,8 +49694,6 @@ MUPARSER_LIBS!$MUPARSER_LIBS$ac_delim
 HDF5_INCLUDE!$HDF5_INCLUDE$ac_delim
 HDF5_LIBS!$HDF5_LIBS$ac_delim
 JPEG_INCLUDE!$JPEG_INCLUDE$ac_delim
-JPEG_LIBS!$JPEG_LIBS$ac_delim
-PNG_INCLUDE!$PNG_INCLUDE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -49541,6 +49735,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+JPEG_LIBS!$JPEG_LIBS$ac_delim
+PNG_INCLUDE!$PNG_INCLUDE$ac_delim
 PNG_LIBS!$PNG_LIBS$ac_delim
 TIFF_INCLUDE!$TIFF_INCLUDE$ac_delim
 TIFF_LIBS!$TIFF_LIBS$ac_delim
@@ -49636,8 +49832,6 @@ XCONNEXT!$XCONNEXT$ac_delim
 serial!$serial$ac_delim
 bdb!$bdb$ac_delim
 dbapi!$dbapi$ac_delim
-objects!$objects$ac_delim
-gui!$gui$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -49679,6 +49873,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+objects!$objects$ac_delim
+gui!$gui$ac_delim
 algo!$algo$ac_delim
 app!$app$ac_delim
 internal!$internal$ac_delim
@@ -49774,8 +49970,6 @@ BOOST_TEST_TEM_STATIC_LIBS!$BOOST_TEST_TEM_STATIC_LIBS$ac_delim
 BOOST_TEST_UTF_LIBS!$BOOST_TEST_UTF_LIBS$ac_delim
 BOOST_TEST_UTF_STATIC_LIBS!$BOOST_TEST_UTF_STATIC_LIBS$ac_delim
 BOOST_THREAD_LIBS!$BOOST_THREAD_LIBS$ac_delim
-BOOST_THREAD_STATIC_LIBS!$BOOST_THREAD_STATIC_LIBS$ac_delim
-NCBI_C_INCLUDE!$NCBI_C_INCLUDE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -49817,6 +50011,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+BOOST_THREAD_STATIC_LIBS!$BOOST_THREAD_STATIC_LIBS$ac_delim
+NCBI_C_INCLUDE!$NCBI_C_INCLUDE$ac_delim
 NCBI_C_LIBPATH!$NCBI_C_LIBPATH$ac_delim
 OPENGL_INCLUDE!$OPENGL_INCLUDE$ac_delim
 OPENGL_LIBS!$OPENGL_LIBS$ac_delim
@@ -49912,8 +50108,6 @@ IF_REBUILDING_CONDITIONALLY!$IF_REBUILDING_CONDITIONALLY$ac_delim
 IF_DEACTIVATING!$IF_DEACTIVATING$ac_delim
 configurables_mfname!$configurables_mfname$ac_delim
 CC_FILTER!$CC_FILTER$ac_delim
-CXX_FILTER!$CXX_FILTER$ac_delim
-AR_FILTER!$AR_FILTER$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -49955,6 +50149,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+CXX_FILTER!$CXX_FILTER$ac_delim
+AR_FILTER!$AR_FILTER$ac_delim
 LINK_FILTER!$LINK_FILTER$ac_delim
 CC_WRAPPER!$CC_WRAPPER$ac_delim
 CXX_WRAPPER!$CXX_WRAPPER$ac_delim
@@ -49979,7 +50175,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 22; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 24; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
