Post-fix for r165907 -- to not require 'internal/*' when a project list is specified.  JIRA: CXX-638
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@79047 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/configure b/src/build-system/configure
--- a/src/build-system/configure
+++ b/src/build-system/configure
@@ -48636,12 +48636,12 @@ else
 echo "$as_me: error: --with-internal:  Cannot build INTERNAL projects: missing $reason" >&2;}
    { (exit 1); exit 1; }; }
       else
-         { echo "$as_me:$LINENO: WARNING: --with-internal:  Cannot build all INTERNAL projects: missing $reason" >&5
-echo "$as_me: WARNING: --with-internal:  Cannot build all INTERNAL projects: missing $reason" >&2;}
+         { echo "$as_me:$LINENO: WARNING: --with-internal:  Cannot build some INTERNAL projects: missing $reason" >&5
+echo "$as_me: WARNING: --with-internal:  Cannot build some INTERNAL projects: missing $reason" >&2;}
          OPT_GROUPS="$OPT_GROUPS internal"
          internal="internal"
       fi
-   elif test -n "$reason"; then
+   elif test -n "$reason" -a -z "$with_projects"; then
       NoConfProjects="$NoConfProjects internal"
       internal=
    else
