Explicitly report leaf failures so that other infrastructure can look up and notify any defined WATCHERS.  JIRA: CXX-1043.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@42906 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/build-system/Makefile.meta.in b/src/build-system/Makefile.meta.in
--- a/src/build-system/Makefile.meta.in
+++ b/src/build-system/Makefile.meta.in
@@ -66,7 +66,8 @@ USRP_BRA = \
       fi ; \
       if NCBICXX_TESTING_REQS=1 $(MAKE_USR) -q requirements ; then \
          $(RWL) -base "make_$$i" $(MAKE_USR)
-USRP_KET = || $(NOTK_BRA) exit 1 $(NOTK_KET) ; \
+USRP_KET = || $(NOTK_BRA) echo 'FAILED: $(srcdir)/Makefile.$$i' ; \
+              exit 1 $(NOTK_KET) ; \
       else \
          echo "NOTE:  skipping project \"$$i\" due to unmet requirements"; \
       fi; \
@@ -81,7 +82,8 @@ ASNP_BRA = \
    for i in $$x_project ; do \
       (cd $(abs_srcdir) \
        && MAKE="$(MAKE) $(MFLAGS_NR)" $(RWL) -base make_asn $(MAKE_ASN)
-ASNP_KET = ) || $(NOTK_BRA) exit 6 $(NOTK_KET) ; \
+ASNP_KET = ) || $(NOTK_BRA) echo 'FAILED: $(srcdir)/Makefile.$$i.lib' ; \
+                exit 6 $(NOTK_KET) ; \
    done ; \
 fi
 
@@ -92,7 +94,8 @@ DTDP_BRA = \
    for i in $$x_project ; do \
       (cd $(abs_srcdir) \
        && MAKE="$(MAKE) $(MFLAGS_NR)" $(RWL) -base make_asn $(MAKE_DTD)
-DTDP_KET = ) || $(NOTK_BRA) exit 6 $(NOTK_KET) ; \
+DTDP_KET = ) || $(NOTK_BRA) echo 'FAILED: $(srcdir)/Makefile.$$i.lib' ; \
+                 exit 6 $(NOTK_KET) ; \
    done ; \
 fi
 
@@ -103,7 +106,8 @@ XSDP_BRA = \
    for i in $$x_project ; do \
       (cd $(abs_srcdir) \
        && MAKE="$(MAKE) $(MFLAGS_NR)" $(RWL) -base make_asn $(MAKE_XSD)
-XSDP_KET = ) || $(NOTK_BRA) exit 6 $(NOTK_KET) ; \
+XSDP_KET = ) || $(NOTK_BRA) echo 'FAILED: $(srcdir)/Makefile.$$i.lib' ; \
+                 exit 6 $(NOTK_KET) ; \
    done ; \
 fi
 
@@ -124,7 +128,8 @@ LIBP_BRA = \
         $(RWL) -base "make_$$i" $(MAKE_LIB)
 LIBP_KET = && continue ; \
         $(MAKE_LIB) $(deactivate) ; \
-        $(NOTK_BRA) exit 2 $(NOTK_KET) ; \
+        $(NOTK_BRA) echo 'FAILED: $(srcdir)/Makefile.$$i.lib' ; \
+        exit 2 $(NOTK_KET) ; \
      else \
        echo "NOTE:  skipping project \"$$i\" due to unmet requirements"; \
      fi; \
@@ -145,7 +150,8 @@ APPP_BRA = \
         $(RWL) -base "make_$$i" $(MAKE_APP)
 APPP_KET = && continue ; \
         $(MAKE_APP) unlink ; \
-        $(NOTK_BRA) exit 3 $(NOTK_KET) ; \
+        $(NOTK_BRA) echo 'FAILED: $(srcdir)/Makefile.$$i.app' ; \
+        exit 3 $(NOTK_KET) ; \
      else \
        echo "NOTE:  skipping project \"$$i\" due to unmet requirements"; \
      fi; \
