Generalize to support DTDs (with new --dtd option) as well as ASN.1 specs.
git-svn-id: https://anonsvn.ncbi.nlm.nih.gov/repos/v1/trunk/c++@18844 78c7ea69-d796-4a43-9a09-de51944f1b03

diff --git a/src/new_module.sh.in b/src/new_module.sh.in
--- a/src/new_module.sh.in
+++ b/src/new_module.sh.in
@@ -53,9 +53,20 @@ getvar () {
 
 # detect command arguments
 case "$1" in
-    *.asn)
-        module="`basename \"$1\" .asn`"
-        asn="$1"
+    --dtd)
+        ext="dtd"
+        EXT="DTD"
+        shift
+        ;;
+    *)
+        ext="asn"
+        EXT="ASN"
+        ;;
+esac
+case "$1" in
+    *.$ext)
+        module="`basename \"$1\" .$ext`"
+        spec="$1"
         shift;;
     *.module)
         module="`basename \"$1\" .module`"
@@ -73,38 +84,49 @@ esac
 
 if test -f "$module.module"; then
     if test -z "$asn"; then
-        asn="`getvar MODULE_ASN \"$module.module\"`"
+        spec="`getvar MODULE_$EXT \"$module.module\"`"
     fi
     imports="`getvar MODULE_IMPORT \"$module.module\"`"
 else
     echo "File $module.module not found. Using defaults..."
 fi
-if test -z "$asn"; then
-    asn="$module.asn"
+if test -z "$spec"; then
+    spec="$module.$ext"
 fi
 
-# now $asn is source ASN.1 file $module.module is module description file
+# now $spec is source ASN.1 specification or DTD,
+# $module.module is module description file
 # check files
-if test -f "$asn"; then
+if test -f "$spec"; then
     :
 else
-    echo "Source file $asn not found."
+    echo "Source file $spec not found."
     exit 1
 fi
 
 # Try to find imports
 impdeps=
+impfiles=
 space=
 need_main=false
 for i in $imports; do
     if test -f "$p/src/$i.asn"; then
-	  impdeps="${impdeps}${space}${p}/src/$i.asn"
+          impdeps="${impdeps}${space}${p}/src/$i.asn"
+          impfiles="${impfiles}${space}$i.asn"
+    elif test -f "$p/src/$i.dtd"; then
+          impdeps="${impdeps}${space}${p}/src/$i.dtd"
+          impfiles="${impfiles}${space}$i.dtd"
     elif test -f "$top_srcdir/src/$i.asn"; then
-	  impdeps="${impdeps}${space}${top_srcdir}/src/$i.asn"
-	  need_main=true
+          impdeps="${impdeps}${space}${top_srcdir}/src/$i.asn"
+          impfiles="${impfiles}${space}$i.asn"
+          need_main=true
+    elif test -f "$top_srcdir/src/$i.dtd"; then
+          impdeps="${impdeps}${space}${top_srcdir}/src/$i.dtd"
+          impfiles="${impfiles}${space}$i.dtd"
+          need_main=true
     else
-	  echo "Import file $i not found."
-	  exit 1
+          echo "Import file $i not found."
+          exit 1
     fi
     space=' '
 done
@@ -142,5 +164,5 @@ else
 fi
 
 # run command
-echo $MAKE -f "$makemodule" "MODULE=$module" "MODULE_PATH=$mp" "MODULE_ASN=$asn" "MODULE_IMPORT='$imports'" "IMPDEPS='$impdeps'" "top_srcdir=$p" "DATATOOL=$datatool" "MODULE_SEARCH=$search" "$@"
-$MAKE -f "$makemodule" "MODULE=$module" "MODULE_PATH=$mp" "MODULE_ASN=$asn" "MODULE_IMPORT=$imports" "IMPDEPS=$impdeps" "top_srcdir=$p" "DATATOOL=$datatool" "MODULE_SEARCH=$search" "$@"
+echo $MAKE -f "$makemodule" "MODULE=$module" "MODULE_PATH=$mp" "MODULE_ASN=$spec" "MODULE_IMPORT='$imports'" "IMPDEPS='$impdeps'" "IMPFILES='$impfiles'" "top_srcdir=$p" "DATATOOL=$datatool" "MODULE_SEARCH=$search" "$@"
+$MAKE -f "$makemodule" "MODULE=$module" "MODULE_PATH=$mp" "MODULE_ASN=$spec" "MODULE_IMPORT=$imports" "IMPDEPS=$impdeps" "IMPFILES='$impfiles'" "top_srcdir=$p" "DATATOOL=$datatool" "MODULE_SEARCH=$search" "$@"
